#!/usr/bin/env dotnet run
#:property AllowUnsafeBlocks=true
#:property UsePskernelSharpUsings=true
#:property UseParasolidScriptHost=true
#:property UseParasolidXtCorpusHost=true
#:project ../../third_party/PKToy/PskernelSharp/PskernelSharp.csproj

using static parasolid;

// Complex geometry is deliberately split into independent cases.  The cases
// that create a surface turn that surface into a sheet body, so the target
// geometry is a face surface rather than an unattached construction object.
var cases = new CorpusCaseSpec[]
{
    new(
        "complex-curve-bcurve",
        "PK_BCURVE_create",
        "Non-rational cubic B-curve with a clamped, non-uniform knot vector.",
        new[] { "curve", "bcurve", "spline", "non-rational", "open", "non-periodic", "construction-geometry" },
        CreateBCurve,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"degree\":3,\"vertices\":[[0.0,0.0,0.0],[1.0,2.0,0.5],[2.0,-1.0,1.0],[4.0,0.0,0.0]],\"knots\":[0.0,1.0],\"multiplicities\":[4,4]}"),
    new(
        "complex-surface-bsurf",
        "PK_BSURF_create + PK_SURF_make_sheet_body",
        "Non-rational biquadratic B-surface with a finite rectangular parameter domain.",
        new[] { "surface", "bsurf", "spline", "non-rational", "open", "non-periodic", "face-surface" },
        CreateBSurf,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"uDegree\":2,\"vDegree\":2,\"uVertices\":3,\"vVertices\":3,\"uvBox\":[0.0,1.0,0.0,1.0],\"owner\":\"face.surface\"}"),
    new(
        "complex-surface-swept",
        "PK_SWEPT_create + PK_SURF_make_sheet_body",
        "Finite swept surface from a line and a unit translation direction.",
        new[] { "surface", "swept", "derived-surface", "line-profile", "face-surface", "finite-parameter-domain" },
        CreateSwept,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"profile\":\"line\",\"direction\":[0.0,0.0,1.0],\"uvBox\":[-2.0,2.0,0.0,3.0],\"owner\":\"face.surface\"}"),
    new(
        "complex-surface-spun",
        "PK_SPUN_create + PK_SURF_make_sheet_body",
        "Finite spun surface from a line profile around an axis-one basis.",
        new[] { "surface", "spun", "derived-surface", "line-profile", "face-surface", "finite-parameter-domain" },
        CreateSpun,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"profile\":\"line\",\"axisLocation\":[0.0,0.0,0.0],\"axisDirection\":[0.0,0.0,1.0],\"uvBox\":[0.0,1.0,0.0,6.283185307179586],\"owner\":\"face.surface\"}"),
    new(
        "complex-curve-spcurve",
        "PK_CURVE_make_spcurves_2",
        "Surface parameter curve made from a line lying on a planar surface.",
        new[] { "curve", "spcurve", "parameter-curve", "plane", "face-surface", "finite-interval" },
        CreateSPCurve,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"curve\":\"line\",\"surface\":\"plane\",\"range\":[-1.5,1.5],\"tolerance\":0.00001}"),
    new(
        "complex-surface-curve-spin",
        "PK_CURVE_spin + PK_SURF_make_sheet_body",
        "Surface generated by spinning a finite line profile around an axis-one basis.",
        new[] { "surface", "spun", "derived-surface", "line-profile", "face-surface" },
        CreateCurveSpin,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"profile\":\"line\",\"axisLocation\":[0.0,0.0,0.0],\"axisDirection\":[0.0,0.0,1.0],\"uvBox\":[-1.0,1.0,0.0,6.283185307179586]}"),
    new(
        "complex-surface-curve-sweep",
        "PK_CURVE_sweep + PK_SURF_make_sheet_body",
        "Surface generated by sweeping a finite line profile along a direction vector.",
        new[] { "surface", "swept", "derived-surface", "line-profile", "face-surface" },
        CreateCurveSweep,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"profile\":\"line\",\"direction\":[0.0,0.0,1.0],\"uvBox\":[-2.0,2.0,0.0,3.0]}"),
    new(
        "complex-surface-curve-spin-2",
        "PK_CURVE_spin_2 + PK_SURF_make_sheet_body",
        "Option-bearing surface generated by spinning a finite line profile.",
        new[] { "surface", "spun", "derived-surface", "line-profile", "options", "face-surface" },
        CreateCurveSpin2,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"profile\":\"line\",\"axisLocation\":[0.0,0.0,0.0],\"axisDirection\":[0.0,0.0,1.0],\"options\":\"default\",\"uvBox\":[-1.0,1.0,0.0,6.283185307179586]}"),
    new(
        "complex-curve-make-bcurve",
        "PK_CURVE_make_bcurve + PK_LINE_create",
        "A B-curve approximation generated from a finite analytic line.",
        new[] { "curve", "bcurve", "approximation", "analytic-input", "construction-geometry" },
        CreateMadeBCurve,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"sourceCurve\":\"line\",\"range\":[-2.0,2.0],\"cubic\":true,\"nonRational\":true,\"tolerance\":0.00001}"),
    new(
        "complex-curve-make-bcurve-2",
        "PK_CURVE_make_bcurve_2 + PK_LINE_create",
        "Option-bearing B-curve approximation generated from a finite analytic line.",
        new[] { "curve", "bcurve", "approximation", "options", "construction-geometry" },
        CreateMadeBCurve2,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"sourceCurve\":\"line\",\"range\":[-2.0,2.0],\"options\":\"default\",\"tolerance\":0.00001}"),
    new(
        "complex-curve-make-spcurves",
        "PK_CURVE_make_spcurves + PK_LINE_create + PK_PLANE_create",
        "Parameter curve generated from a line on a planar surface using the legacy producer.",
        new[] { "curve", "spcurve", "parameter-curve", "plane", "construction-geometry" },
        CreateSPCurveLegacy,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"curve\":\"line\",\"surface\":\"plane\",\"range\":[-1.5,1.5],\"degenerate\":false,\"sense\":false,\"tolerance\":0.00001}"),
    new(
        "complex-surface-bsurf-add-knots",
        "PK_BSURF_create + PK_BSURF_add_u_knot + PK_BSURF_add_v_knot + PK_BSURF_remove_knots + PK_BSURF_raise_degree + PK_BSURF_lower_degree + PK_BSURF_set_approx",
        "A B-surface with explicit interior U and V knot insertions.",
        new[] { "surface", "bsurf", "spline", "knot-insertion", "construction-geometry" },
        CreateBSurfWithKnots,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"source\":\"non-rational-bsurf\",\"insertU\":0.5,\"insertV\":0.5}"),
    new(
        "complex-curve-bcurve-add-knot",
        "PK_BCURVE_create + PK_BCURVE_add_knot",
        "A non-rational B-curve with an explicit interior knot insertion.",
        new[] { "curve", "bcurve", "spline", "knot-insertion", "construction-geometry" },
        CreateBCurveWithKnot,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"source\":\"non-rational-bcurve\",\"insertKnot\":0.5}"),
    new(
        "complex-curve-bcurve-remove-knot",
        "PK_BCURVE_create + PK_BCURVE_add_knot + PK_BCURVE_remove_knots",
        "A B-curve with an interior knot removed using the default removal policy.",
        new[] { "curve", "bcurve", "spline", "knot-removal", "construction-geometry" },
        CreateBCurveWithoutInteriorKnot,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"source\":\"non-rational-bcurve\",\"insertKnot\":0.5,\"removeKnots\":\"default\"}"),
    new(
        "complex-curve-bcurve-set-approx",
        "PK_BCURVE_create + PK_BCURVE_set_approx",
        "A B-curve with explicit approximation segment and derivative metadata.",
        new[] { "curve", "bcurve", "spline", "approximation", "construction-geometry" },
        CreateBCurveWithApproximation,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"source\":\"non-rational-bcurve\",\"segments\":1,\"derivatives\":1}"),
    new(
        "complex-curve-make-bcurve-array",
        "PK_CURVE_make_bcurve_array + PK_LINE_create",
        "Array-form B-curve approximation for one finite analytic line.",
        new[] { "curve", "bcurve", "approximation", "array-api", "construction-geometry" },
        CreateMadeBCurveArray,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"count\":1,\"sourceCurve\":\"line\",\"range\":[-2.0,2.0],\"tolerance\":0.00001}"),
    new(
        "complex-curve-make-approx",
        "PK_CURVE_make_approx + PK_LINE_create",
        "Arc-length approximation of a finite analytic line with explicit continuity.",
        new[] { "curve", "approximation", "line", "options", "construction-geometry" },
        CreateCurveApproximation,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"sourceCurve\":\"line\",\"range\":[-2.0,2.0],\"approxType\":\"arclength\",\"tolerance\":0.00001,\"continuity\":\"c1\"}"),
    new(
        "complex-surface-bcurve-spin",
        "PK_BCURVE_create + PK_BCURVE_spin",
        "B-surface generated by spinning a non-rational B-curve through a finite angle.",
        new[] { "surface", "bsurf", "bcurve", "spin", "derived-surface", "construction-geometry" },
        CreateBCurveSpin,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"profile\":\"non-rational-bcurve\",\"axisDirection\":[0.0,0.0,1.0],\"angle\":0.5}"),
    new(
        "complex-surface-bcurve-sweep",
        "PK_BCURVE_create + PK_BCURVE_sweep",
        "B-surface generated by sweeping a non-rational B-curve along a path vector.",
        new[] { "surface", "bsurf", "bcurve", "sweep", "derived-surface", "construction-geometry" },
        CreateBCurveSweep,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"profile\":\"non-rational-bcurve\",\"path\":[0.0,0.0,2.0]}"),
    new(
        "complex-curve-bcurve-piecewise",
        "PK_BCURVE_create_piecewise",
        "A single-segment cubic Bezier B-curve supplied through the piecewise standard form.",
        new[] { "curve", "bcurve", "piecewise", "bezier", "construction-geometry" },
        CreatePiecewiseBCurve,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"degree\":3,\"segments\":1,\"representation\":\"bezier\",\"rational\":false}"),
    new(
        "complex-curve-bcurve-splinewise",
        "PK_BCURVE_create_splinewise",
        "A cubic B-curve interpolated from four positions using automatic knot generation.",
        new[] { "curve", "bcurve", "splinewise", "interpolation", "construction-geometry" },
        CreateSplinewiseBCurve,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"degree\":3,\"positions\":4,\"knot\":\"auto\",\"endConditions\":\"natural\"}"),
    new(
        "complex-curve-bcurve-spline",
        "PK_BCURVE_create_spline",
        "A cubic B-curve interpolated from four positions with the spline producer.",
        new[] { "curve", "bcurve", "spline", "interpolation", "construction-geometry" },
        CreateSplineBCurve,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"degree\":3,\"positions\":4,\"paramInterval\":[0.0,1.0],\"periodic\":false}"),
    new(
        "complex-curve-bcurve-spline-2",
        "PK_BCURVE_create_spline_2",
        "The option-bearing spline producer interpolating four positions into one B-curve.",
        new[] { "curve", "bcurve", "spline", "interpolation", "options", "construction-geometry" },
        CreateSplineBCurve2,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"degree\":3,\"positions\":4,\"paramInterval\":[0.0,1.0],\"periodic\":false,\"options\":\"default\"}"),
    new(
        "complex-curve-bcurve-fitted",
        "PK_BCURVE_create_fitted + PK_LINE_create",
        "A fitted B-curve generated from a finite analytic line through the general-curve input contract.",
        new[] { "curve", "bcurve", "fitted", "analytic-input", "construction-geometry" },
        CreateFittedBCurve,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"sourceCurve\":\"line\",\"range\":[-2.0,2.0],\"tolerance\":0.000001,\"preserveParameterisation\":true}"),
    new(
        "complex-surface-bsurf-piecewise",
        "PK_BSURF_create_piecewise",
        "A single-segment bicubic Bezier surface supplied through the piecewise standard form.",
        new[] { "surface", "bsurf", "piecewise", "bezier", "construction-geometry" },
        CreatePiecewiseBSurf,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"uDegree\":2,\"vDegree\":2,\"uSegments\":1,\"vSegments\":1,\"representation\":\"bezier\"}"),
    new(
        "complex-surface-bsurf-splinewise",
        "PK_BSURF_create_splinewise",
        "A bicquadratic B-surface interpolated from a 3x3 position grid with automatic knots.",
        new[] { "surface", "bsurf", "splinewise", "interpolation", "construction-geometry" },
        CreateSplinewiseBSurf,
        new CorpusBodyCounts(1, 1, 1, 4, 4),
        null,
        "{\"uDegree\":2,\"vDegree\":2,\"uPositions\":3,\"vPositions\":3,\"knots\":\"auto\"}"),
};

return ParasolidXtCorpusHost.RunGroup("complex-geometry", cases, args);

static unsafe PK_BODY_t CreateBCurve()
{
    var vertices = stackalloc double[]
    {
        0.0, 0.0, 0.0,
        1.0, 2.0, 0.5,
        2.0, -1.0, 1.0,
        4.0, 0.0, 0.0,
    };
    var knotMultiplicities = stackalloc int[] { 4, 4 };
    var knots = stackalloc double[] { 0.0, 1.0 };
    var standardForm = new PK_BCURVE_sf_t(
        3,
        4,
        3,
        PK_LOGICAL_false,
        vertices,
        PK_BCURVE_form_arbitrary_c,
        2,
        knotMultiplicities,
        knots,
        PK_knot_non_uniform_c,
        PK_LOGICAL_false,
        PK_LOGICAL_false,
        PK_self_intersect_false_c);
    PK_BCURVE_t bcurve;
    ParasolidXtCorpusHost.Check(PK_BCURVE_create(&standardForm, &bcurve), "PK_BCURVE_create");
    return AddConstructionGeometry(bcurve);
}

static unsafe PK_BODY_t CreateBSurf()
{
    var vertices = stackalloc double[]
    {
        0.0, 0.0, 0.0,  1.0, 0.0, 0.5,  2.0, 0.0, 0.0,
        0.0, 1.0, 0.4,  1.0, 1.0, 1.2, 2.0, 1.0, 0.3,
        0.0, 2.0, 0.0,  1.0, 2.0, 0.6,  2.0, 2.0, 0.0,
    };
    var uKnotMultiplicities = stackalloc int[] { 3, 3 };
    var vKnotMultiplicities = stackalloc int[] { 3, 3 };
    var uKnots = stackalloc double[] { 0.0, 1.0 };
    var vKnots = stackalloc double[] { 0.0, 1.0 };
    var standardForm = new PK_BSURF_sf_t(
        2,
        2,
        3,
        3,
        3,
        PK_LOGICAL_false,
        vertices,
        PK_BSURF_form_arbitrary_c,
        2,
        2,
        uKnotMultiplicities,
        vKnotMultiplicities,
        uKnots,
        vKnots,
        PK_knot_non_uniform_c,
        PK_knot_non_uniform_c,
        PK_LOGICAL_false,
        PK_LOGICAL_false,
        PK_LOGICAL_false,
        PK_LOGICAL_false,
        PK_self_intersect_false_c,
        PK_convexity_arbitrary_c);
    PK_BSURF_t bsurf;
    ParasolidXtCorpusHost.Check(PK_BSURF_create(&standardForm, &bsurf), "PK_BSURF_create");
    return AddConstructionGeometry(bsurf);
}


static unsafe PK_BODY_t CreateSwept()
{
    var lineForm = new PK_LINE_sf_t(new PK_AXIS1_sf_t(
        new PK_VECTOR_t(-2.0, 0.0, 0.0),
        new PK_VECTOR1_t(1.0, 0.0, 0.0)));
    PK_LINE_t line;
    ParasolidXtCorpusHost.Check(PK_LINE_create(&lineForm, &line), "PK_LINE_create for swept");
    var sweptForm = new PK_SWEPT_sf_t(line, new PK_VECTOR1_t(0.0, 0.0, 1.0));
    PK_SWEPT_t swept;
    ParasolidXtCorpusHost.Check(PK_SWEPT_create(&sweptForm, &swept), "PK_SWEPT_create");
    return MakeSheetBody(swept, new PK_UVBOX_t(-2.0, 2.0, 0.0, 3.0));
}

static unsafe PK_BODY_t CreateSpun()
{
    var lineForm = new PK_LINE_sf_t(new PK_AXIS1_sf_t(
        new PK_VECTOR_t(2.0, 0.0, 0.0),
        new PK_VECTOR1_t(0.0, 0.0, 1.0)));
    PK_LINE_t line;
    ParasolidXtCorpusHost.Check(PK_LINE_create(&lineForm, &line), "PK_LINE_create for spun");
    var spunForm = new PK_SPUN_sf_t(
        line,
        new PK_AXIS1_sf_t(
            new PK_VECTOR_t(0.0, 0.0, 0.0),
            new PK_VECTOR1_t(0.0, 0.0, 1.0)));
    PK_SPUN_t spun;
    ParasolidXtCorpusHost.Check(PK_SPUN_create(&spunForm, &spun), "PK_SPUN_create");
    return MakeSheetBody(spun, new PK_UVBOX_t(-1.0, 1.0, 0.0, 6.283185307179586));
}

static unsafe PK_BODY_t CreateSPCurve()
{
    var planeForm = new PK_PLANE_sf_t(new PK_AXIS2_sf_t(
        new PK_VECTOR_t(0.0, 0.0, 0.0),
        new PK_VECTOR1_t(0.0, 0.0, 1.0),
        new PK_VECTOR1_t(1.0, 0.0, 0.0)));
    PK_PLANE_t plane;
    ParasolidXtCorpusHost.Check(PK_PLANE_create(&planeForm, &plane), "PK_PLANE_create for spcurve");
    var lineForm = new PK_LINE_sf_t(new PK_AXIS1_sf_t(
        new PK_VECTOR_t(-1.5, 0.0, 0.0),
        new PK_VECTOR1_t(1.0, 0.0, 0.0)));
    PK_LINE_t line;
    ParasolidXtCorpusHost.Check(PK_LINE_create(&lineForm, &line), "PK_LINE_create for spcurve");

    var options = new PK_CURVE_make_spcurves_o_t();
    int count;
    PK_SPCURVE_t* spcurves;
    ParasolidXtCorpusHost.Check(
        PK_CURVE_make_spcurves_2(line, new PK_INTERVAL_t(-1.5, 1.5), plane, 1.0e-5, &options, &count, &spcurves),
        "PK_CURVE_make_spcurves_2");
    try
    {
        if (count != 1)
            throw new InvalidOperationException("expected one SP-curve, got " + count);
        return AddConstructionGeometry(spcurves[0]);
    }
    finally
    {
        if (spcurves is not null)
            ParasolidXtCorpusHost.Check(PK_MEMORY_free(spcurves), "PK_MEMORY_free spcurves");
    }
}

static unsafe PK_BODY_t CreateCurveSpin()
{
    var lineForm = new PK_LINE_sf_t(new PK_AXIS1_sf_t(
        new PK_VECTOR_t(2.0, 0.0, 0.0),
        new PK_VECTOR1_t(0.0, 0.0, 1.0)));
    PK_LINE_t line;
    ParasolidXtCorpusHost.Check(PK_LINE_create(&lineForm, &line), "PK_LINE_create curve spin");
    var axis = new PK_AXIS1_sf_t(new PK_VECTOR_t(0.0, 0.0, 0.0), new PK_VECTOR1_t(0.0, 0.0, 1.0));
    PK_SURF_t surface;
    ParasolidXtCorpusHost.Check(PK_CURVE_spin(line, &axis, &surface), "PK_CURVE_spin");
    return MakeSheetBody(surface, new PK_UVBOX_t(-1.0, 1.0, 0.0, 6.283185307179586));
}

static unsafe PK_BODY_t CreateCurveSweep()
{
    var lineForm = new PK_LINE_sf_t(new PK_AXIS1_sf_t(
        new PK_VECTOR_t(-2.0, 0.0, 0.0),
        new PK_VECTOR1_t(1.0, 0.0, 0.0)));
    PK_LINE_t line;
    ParasolidXtCorpusHost.Check(PK_LINE_create(&lineForm, &line), "PK_LINE_create curve sweep");
    PK_SURF_t surface;
    ParasolidXtCorpusHost.Check(PK_CURVE_sweep(line, new PK_VECTOR1_t(0.0, 0.0, 1.0), &surface), "PK_CURVE_sweep");
    return MakeSheetBody(surface, new PK_UVBOX_t(-2.0, 2.0, 0.0, 3.0));
}

static unsafe PK_BODY_t CreateCurveSpin2()
{
    var lineForm = new PK_LINE_sf_t(new PK_AXIS1_sf_t(
        new PK_VECTOR_t(2.0, 0.0, 0.0),
        new PK_VECTOR1_t(0.0, 0.0, 1.0)));
    PK_LINE_t line;
    ParasolidXtCorpusHost.Check(PK_LINE_create(&lineForm, &line), "PK_LINE_create curve spin 2");
    var axis = new PK_AXIS1_sf_t(new PK_VECTOR_t(0.0, 0.0, 0.0), new PK_VECTOR1_t(0.0, 0.0, 1.0));
    var options = new PK_CURVE_spin_o_t();
    PK_SURF_t surface;
    ParasolidXtCorpusHost.Check(PK_CURVE_spin_2(line, &axis, &options, &surface), "PK_CURVE_spin_2");
    return MakeSheetBody(surface, new PK_UVBOX_t(-1.0, 1.0, 0.0, 6.283185307179586));
}


static unsafe PK_BODY_t CreateMadeBCurve()
{
    var lineForm = new PK_LINE_sf_t(new PK_AXIS1_sf_t(
        new PK_VECTOR_t(-2.0, 0.0, 0.0),
        new PK_VECTOR1_t(1.0, 0.0, 0.0)));
    PK_LINE_t line;
    ParasolidXtCorpusHost.Check(PK_LINE_create(&lineForm, &line), "PK_LINE_create make bcurve");
    PK_BCURVE_t bcurve;
    PK_LOGICAL_t exact;
    ParasolidXtCorpusHost.Check(PK_CURVE_make_bcurve(line, new PK_INTERVAL_t(-2.0, 2.0), PK_LOGICAL_true, PK_LOGICAL_true, 0.00001, &bcurve, &exact), "PK_CURVE_make_bcurve");
    return AddConstructionGeometry(bcurve);
}

static unsafe PK_BODY_t CreateMadeBCurve2()
{
    var lineForm = new PK_LINE_sf_t(new PK_AXIS1_sf_t(
        new PK_VECTOR_t(-2.0, 0.0, 0.0),
        new PK_VECTOR1_t(1.0, 0.0, 0.0)));
    PK_LINE_t line;
    ParasolidXtCorpusHost.Check(PK_LINE_create(&lineForm, &line), "PK_LINE_create make bcurve 2");
    var options = new PK_CURVE_make_bcurve_o_t();
    PK_CURVE_make_bcurve_t status;
    PK_BCURVE_t bcurve;
    double achievedTolerance;
    PK_achieved_cont_t achievedContinuity;
    ParasolidXtCorpusHost.Check(PK_CURVE_make_bcurve_2(line, new PK_INTERVAL_t(-2.0, 2.0), &options, &status, &bcurve, &achievedTolerance, &achievedContinuity), "PK_CURVE_make_bcurve_2");
    return AddConstructionGeometry(bcurve);
}

static unsafe PK_BODY_t CreateSPCurveLegacy()
{
    var planeForm = new PK_PLANE_sf_t(new PK_AXIS2_sf_t(
        new PK_VECTOR_t(0.0, 0.0, 0.0),
        new PK_VECTOR1_t(0.0, 0.0, 1.0),
        new PK_VECTOR1_t(1.0, 0.0, 0.0)));
    PK_PLANE_t plane;
    ParasolidXtCorpusHost.Check(PK_PLANE_create(&planeForm, &plane), "PK_PLANE_create legacy spcurve");
    var lineForm = new PK_LINE_sf_t(new PK_AXIS1_sf_t(
        new PK_VECTOR_t(-1.5, 0.0, 0.0),
        new PK_VECTOR1_t(1.0, 0.0, 0.0)));
    PK_LINE_t line;
    ParasolidXtCorpusHost.Check(PK_LINE_create(&lineForm, &line), "PK_LINE_create legacy spcurve");
    int count;
    PK_SPCURVE_t* curves;
    ParasolidXtCorpusHost.Check(PK_CURVE_make_spcurves(line, new PK_INTERVAL_t(-1.5, 1.5), plane, PK_LOGICAL_false, PK_LOGICAL_false, 0.00001, &count, &curves), "PK_CURVE_make_spcurves");
    try
    {
        if (count != 1)
            throw new InvalidOperationException("expected one legacy SP-curve, got " + count);
        return AddConstructionGeometry(curves[0]);
    }
    finally
    {
        if (curves is not null)
            ParasolidXtCorpusHost.Check(PK_MEMORY_free(curves), "PK_MEMORY_free legacy spcurves");
    }
}

static unsafe PK_BODY_t CreateBSurfWithKnots()
{
    var vertices = stackalloc double[]
    {
        0.0, 0.0, 0.0,  1.0, 0.0, 0.5,  2.0, 0.0, 0.0,
        0.0, 1.0, 0.4,  1.0, 1.0, 1.2, 2.0, 1.0, 0.3,
        0.0, 2.0, 0.0,  1.0, 2.0, 0.6,  2.0, 2.0, 0.0,
    };
    var uKnotMultiplicities = stackalloc int[] { 3, 3 };
    var vKnotMultiplicities = stackalloc int[] { 3, 3 };
    var uKnots = stackalloc double[] { 0.0, 1.0 };
    var vKnots = stackalloc double[] { 0.0, 1.0 };
    var standardForm = new PK_BSURF_sf_t(
        2, 2, 3, 3, 3, PK_LOGICAL_false, vertices, PK_BSURF_form_arbitrary_c,
        2, 2, uKnotMultiplicities, vKnotMultiplicities, uKnots, vKnots,
        PK_knot_non_uniform_c, PK_knot_non_uniform_c, PK_LOGICAL_false,
        PK_LOGICAL_false, PK_LOGICAL_false, PK_LOGICAL_false,
        PK_self_intersect_false_c, PK_convexity_arbitrary_c);
    PK_BSURF_t bsurf;
    ParasolidXtCorpusHost.Check(PK_BSURF_create(&standardForm, &bsurf), "PK_BSURF_create knots");
    ParasolidXtCorpusHost.Check(PK_BSURF_add_u_knot(bsurf, 0.5), "PK_BSURF_add_u_knot");
    ParasolidXtCorpusHost.Check(PK_BSURF_add_v_knot(bsurf, 0.5), "PK_BSURF_add_v_knot");
    var removeOptions = new PK_BSURF_remove_knots_o_t();
    int removedCount;
    double* removedKnots;
    int* removedMultiplicities;
    ParasolidXtCorpusHost.Check(PK_BSURF_remove_knots(bsurf, PK_PARAM_direction_u_c, &removeOptions, &removedCount, &removedKnots, &removedMultiplicities), "PK_BSURF_remove_knots");
    if (removedKnots is not null) ParasolidXtCorpusHost.Check(PK_MEMORY_free(removedKnots), "PK_MEMORY_free bsurf removed knots");
    if (removedMultiplicities is not null) ParasolidXtCorpusHost.Check(PK_MEMORY_free(removedMultiplicities), "PK_MEMORY_free bsurf removed multiplicities");
    var raiseOptions = new PK_BSURF_raise_degree_o_t();
    ParasolidXtCorpusHost.Check(PK_BSURF_raise_degree(bsurf, PK_PARAM_direction_u_c, 1, &raiseOptions), "PK_BSURF_raise_degree");
    var lowerOptions = new PK_BSURF_lower_degree_o_t();
    ParasolidXtCorpusHost.Check(PK_BSURF_lower_degree(bsurf, PK_PARAM_direction_u_c, 1, &lowerOptions), "PK_BSURF_lower_degree");
    ParasolidXtCorpusHost.Check(PK_BSURF_set_approx(bsurf, 1, 1, PK_LOGICAL_false), "PK_BSURF_set_approx");
    return AddConstructionGeometry(bsurf);
}

static unsafe PK_BODY_t CreateBCurveWithKnot()
{
    var vertices = stackalloc double[]
    {
        0.0, 0.0, 0.0,
        1.0, 2.0, 0.5,
        2.0, -1.0, 1.0,
        4.0, 0.0, 0.0,
    };
    var knotMultiplicities = stackalloc int[] { 4, 4 };
    var knots = stackalloc double[] { 0.0, 1.0 };
    var standardForm = new PK_BCURVE_sf_t(
        3, 4, 3, PK_LOGICAL_false, vertices, PK_BCURVE_form_arbitrary_c,
        2, knotMultiplicities, knots, PK_knot_non_uniform_c,
        PK_LOGICAL_false, PK_LOGICAL_false, PK_self_intersect_false_c);
    PK_BCURVE_t bcurve;
    ParasolidXtCorpusHost.Check(PK_BCURVE_create(&standardForm, &bcurve), "PK_BCURVE_create add knot");
    ParasolidXtCorpusHost.Check(PK_BCURVE_add_knot(bcurve, 0.5), "PK_BCURVE_add_knot");
    return AddConstructionGeometry(bcurve);
}

static unsafe PK_BODY_t CreateBCurveWithoutInteriorKnot()
{
    var vertices = stackalloc double[]
    {
        0.0, 0.0, 0.0,
        1.0, 2.0, 0.5,
        2.0, -1.0, 1.0,
        4.0, 0.0, 0.0,
    };
    var knotMultiplicities = stackalloc int[] { 4, 4 };
    var knots = stackalloc double[] { 0.0, 1.0 };
    var standardForm = new PK_BCURVE_sf_t(
        3, 4, 3, PK_LOGICAL_false, vertices, PK_BCURVE_form_arbitrary_c,
        2, knotMultiplicities, knots, PK_knot_non_uniform_c,
        PK_LOGICAL_false, PK_LOGICAL_false, PK_self_intersect_false_c);
    PK_BCURVE_t bcurve;
    ParasolidXtCorpusHost.Check(PK_BCURVE_create(&standardForm, &bcurve), "PK_BCURVE_create remove knot");
    ParasolidXtCorpusHost.Check(PK_BCURVE_add_knot(bcurve, 0.5), "PK_BCURVE_add_knot remove");
    var options = new PK_BCURVE_remove_knots_o_t();
    int removed;
    double* knotsRemoved;
    int* multiplicities;
    ParasolidXtCorpusHost.Check(PK_BCURVE_remove_knots(bcurve, &options, &removed, &knotsRemoved, &multiplicities), "PK_BCURVE_remove_knots");
    if (knotsRemoved is not null) ParasolidXtCorpusHost.Check(PK_MEMORY_free(knotsRemoved), "PK_MEMORY_free removed knots");
    if (multiplicities is not null) ParasolidXtCorpusHost.Check(PK_MEMORY_free(multiplicities), "PK_MEMORY_free removed multiplicities");
    return AddConstructionGeometry(bcurve);
}

static unsafe PK_BODY_t CreateBCurveWithApproximation()
{
    var vertices = stackalloc double[]
    {
        0.0, 0.0, 0.0,
        1.0, 2.0, 0.5,
        2.0, -1.0, 1.0,
        4.0, 0.0, 0.0,
    };
    var knotMultiplicities = stackalloc int[] { 4, 4 };
    var knots = stackalloc double[] { 0.0, 1.0 };
    var standardForm = new PK_BCURVE_sf_t(
        3, 4, 3, PK_LOGICAL_false, vertices, PK_BCURVE_form_arbitrary_c,
        2, knotMultiplicities, knots, PK_knot_non_uniform_c,
        PK_LOGICAL_false, PK_LOGICAL_false, PK_self_intersect_false_c);
    PK_BCURVE_t bcurve;
    ParasolidXtCorpusHost.Check(PK_BCURVE_create(&standardForm, &bcurve), "PK_BCURVE_create approximation");
    ParasolidXtCorpusHost.Check(PK_BCURVE_set_approx(bcurve, 1, 1), "PK_BCURVE_set_approx");
    return AddConstructionGeometry(bcurve);
}

static unsafe PK_BODY_t CreateMadeBCurveArray()
{
    var lineForm = new PK_LINE_sf_t(new PK_AXIS1_sf_t(
        new PK_VECTOR_t(-2.0, 0.0, 0.0),
        new PK_VECTOR1_t(1.0, 0.0, 0.0)));
    PK_LINE_t line;
    ParasolidXtCorpusHost.Check(PK_LINE_create(&lineForm, &line), "PK_LINE_create bcurve array");
    var curves = stackalloc PK_CURVE_t[1] { line };
    var ranges = stackalloc PK_INTERVAL_t[1] { new PK_INTERVAL_t(-2.0, 2.0) };
    var options = new PK_CURVE_make_bcurve_array_o_t();
    var results = stackalloc PK_CURVE_make_bcurve_res_t[1];
    PK_LOGICAL_t allSucceeded;
    ParasolidXtCorpusHost.Check(PK_CURVE_make_bcurve_array(1, curves, ranges, &options, results, &allSucceeded), "PK_CURVE_make_bcurve_array");
    if ((int)allSucceeded != 1 || results[0].bcurve <= 0)
        throw new InvalidOperationException("bcurve array conversion did not succeed");
    return AddConstructionGeometry(results[0].bcurve);
}

static unsafe PK_BODY_t CreateCurveApproximation()
{
    var lineForm = new PK_LINE_sf_t(new PK_AXIS1_sf_t(
        new PK_VECTOR_t(-2.0, 0.0, 0.0),
        new PK_VECTOR1_t(1.0, 0.0, 0.0)));
    PK_LINE_t line;
    ParasolidXtCorpusHost.Check(PK_LINE_create(&lineForm, &line), "PK_LINE_create curve approx");
    var options = new PK_CURVE_make_approx_o_t(PK_CURVE_approx_arclength_c, 0.00001, PK_continuity_c1_c);
    PK_CURVE_t newCurve;
    PK_INTERVAL_t newInterval;
    PK_LOGICAL_t exact;
    ParasolidXtCorpusHost.Check(PK_CURVE_make_approx(line, new PK_INTERVAL_t(-2.0, 2.0), &options, &newCurve, &newInterval, &exact), "PK_CURVE_make_approx");
    return AddConstructionGeometry(newCurve);
}

static unsafe PK_BCURVE_t CreateRawBCurve()
{
    var vertices = stackalloc double[]
    {
        0.0, 0.0, 0.0,
        1.0, 2.0, 0.5,
        2.0, -1.0, 1.0,
        4.0, 0.0, 0.0,
    };
    var knotMultiplicities = stackalloc int[] { 4, 4 };
    var knots = stackalloc double[] { 0.0, 1.0 };
    var standardForm = new PK_BCURVE_sf_t(
        3, 4, 3, PK_LOGICAL_false, vertices, PK_BCURVE_form_arbitrary_c,
        2, knotMultiplicities, knots, PK_knot_non_uniform_c,
        PK_LOGICAL_false, PK_LOGICAL_false, PK_self_intersect_false_c);
    PK_BCURVE_t bcurve;
    ParasolidXtCorpusHost.Check(PK_BCURVE_create(&standardForm, &bcurve), "PK_BCURVE_create derived surface");
    return bcurve;
}

static unsafe PK_BODY_t CreateBCurveSpin()
{
    var bcurve = CreateRawBCurve();
    var axis = new PK_AXIS1_sf_t(new PK_VECTOR_t(0.0, 0.0, 0.0), new PK_VECTOR1_t(0.0, 0.0, 1.0));
    PK_BSURF_t bsurf;
    ParasolidXtCorpusHost.Check(PK_BCURVE_spin(bcurve, &axis, 0.5, &bsurf), "PK_BCURVE_spin");
    return AddConstructionGeometry(bsurf);
}

static unsafe PK_BODY_t CreateBCurveSweep()
{
    var bcurve = CreateRawBCurve();
    PK_BSURF_t bsurf;
    ParasolidXtCorpusHost.Check(PK_BCURVE_sweep(bcurve, new PK_VECTOR_t(0.0, 0.0, 2.0), &bsurf), "PK_BCURVE_sweep");
    return AddConstructionGeometry(bsurf);
}

static unsafe PK_BODY_t CreatePiecewiseBCurve()
{
    var coefficients = stackalloc double[]
    {
        0.0, 0.0, 0.0,
        1.0, 2.0, 0.5,
        2.0, -1.0, 1.0,
        4.0, 0.0, 0.0,
    };
    var standardForm = new PK_BCURVE_piecewise_sf_t(
        3,
        1,
        3,
        PK_LOGICAL_false,
        PK_piecewise_rep_bezier_c,
        coefficients);
    PK_BCURVE_t bcurve;
    ParasolidXtCorpusHost.Check(
        PK_BCURVE_create_piecewise(&standardForm, &bcurve),
        "PK_BCURVE_create_piecewise");
    return AddConstructionGeometry(bcurve);
}

static unsafe PK_BODY_t CreateSplinewiseBCurve()
{
    var positions = stackalloc PK_VECTOR_t[]
    {
        new PK_VECTOR_t(0.0, 0.0, 0.0),
        new PK_VECTOR_t(1.0, 2.0, 0.5),
        new PK_VECTOR_t(2.0, -1.0, 1.0),
        new PK_VECTOR_t(4.0, 0.0, 0.0),
    };
    var standardForm = new PK_BCURVE_splinewise_sf_t(
        3,
        4,
        positions,
        PK_PARAM_end_natural_c,
        PK_PARAM_end_natural_c,
        new PK_VECTOR_t(0.0, 0.0, 0.0),
        new PK_VECTOR_t(0.0, 0.0, 0.0),
        PK_PARAM_knot_auto_c,
        null);
    PK_BCURVE_t bcurve;
    ParasolidXtCorpusHost.Check(
        PK_BCURVE_create_splinewise(&standardForm, &bcurve),
        "PK_BCURVE_create_splinewise");
    return AddConstructionGeometry(bcurve);
}

static unsafe PK_BODY_t CreateSplineBCurve()
{
    var positions = stackalloc PK_VECTOR_t[]
    {
        new PK_VECTOR_t(0.0, 0.0, 0.0),
        new PK_VECTOR_t(1.0, 2.0, 0.5),
        new PK_VECTOR_t(2.0, -1.0, 1.0),
        new PK_VECTOR_t(4.0, 0.0, 0.0),
    };
    var options = new PK_BCURVE_create_spline_o_t
    {
        o_t_version = 3,
        param_interval = new PK_INTERVAL_t(0.0, 1.0),
        degree = 3,
        is_periodic = PK_LOGICAL_false,
        overdefined = PK_BCURVE_overdefined_fail_c,
        clamp = PK_BCURVE_clamp_no_c,
        have_clamp_axes = PK_LOGICAL_false,
    };
    PK_BCURVE_t bcurve;
    PK_BCURVE_spline_t status;
    int faultCount;
    int* faultValues;
    ParasolidXtCorpusHost.Check(
        PK_BCURVE_create_spline(4, positions, &options, &bcurve, &status, &faultCount, &faultValues),
        "PK_BCURVE_create_spline");
    if (faultValues is not null)
        ParasolidXtCorpusHost.Check(PK_MEMORY_free(faultValues), "PK_MEMORY_free spline fault values");
    if (status != PK_BCURVE_spline_ok_c)
        throw new InvalidOperationException("spline status was " + status);
    return AddConstructionGeometry(bcurve);
}

static unsafe PK_BODY_t CreateSplineBCurve2()
{
    var positions = stackalloc PK_VECTOR_t[]
    {
        new PK_VECTOR_t(0.0, 0.0, 0.0),
        new PK_VECTOR_t(1.0, 2.0, 0.5),
        new PK_VECTOR_t(2.0, -1.0, 1.0),
        new PK_VECTOR_t(4.0, 0.0, 0.0),
    };
    var options = new PK_BCURVE_create_spline_2_o_t
    {
        o_t_version = 2,
        param_interval = new PK_INTERVAL_t(0.0, 1.0),
        spline_method = PK_spline_method_interpolate_c,
        degree = 3,
        is_periodic = PK_LOGICAL_false,
        overdefined = PK_BCURVE_overdefined_fail_c,
        clamp = PK_BCURVE_clamp_no_c,
        have_clamp_axes = PK_LOGICAL_false,
        update = PK_spline_update_default_c,
    };
    var results = new PK_BCURVE_spline_r_t();
    ParasolidXtCorpusHost.Check(
        PK_BCURVE_create_spline_2(4, positions, &options, &results),
        "PK_BCURVE_create_spline_2");
    try
    {
        if (results.n_bcurves != 1 || results.bcurves is null)
            throw new InvalidOperationException("expected one spline result, got " + results.n_bcurves);
        if (results.bcurves[0].status != PK_BCURVE_spline_stat_exact_c && results.bcurves[0].status != PK_BCURVE_spline_stat_approx_c)
            throw new InvalidOperationException("unexpected spline-2 status " + results.bcurves[0].status);
        return AddConstructionGeometry(results.bcurves[0].bcurve);
    }
    finally
    {
        if (results.bcurves is not null)
            ParasolidXtCorpusHost.Check(PK_MEMORY_free(results.bcurves), "PK_MEMORY_free spline-2 curves");
        if (results.fault_values is not null)
            ParasolidXtCorpusHost.Check(PK_MEMORY_free(results.fault_values), "PK_MEMORY_free spline-2 faults");
    }
}

static unsafe PK_BODY_t CreateFittedBCurve()
{
    var lineForm = new PK_LINE_sf_t(new PK_AXIS1_sf_t(
        new PK_VECTOR_t(-2.0, 0.0, 0.0),
        new PK_VECTOR1_t(1.0, 0.0, 0.0)));
    PK_LINE_t line;
    ParasolidXtCorpusHost.Check(PK_LINE_create(&lineForm, &line), "PK_LINE_create fitted bcurve");
    var generalCurve = new PK_CURVE_general_t(
        PK_CURVE_general_curve_c,
        new PK_CURVE_general_subunion001_t(line));
    var options = new PK_BCURVE_create_fitted_o_t
    {
        o_t_version = 2,
        curve = generalCurve,
        range = new PK_INTERVAL_t(-2.0, 2.0),
        tolerance = 0.000001,
        angular_tolerance = 0.0,
        n_interpolation_parms = 0,
        interpolation_parms = null,
        preserve_parameterisation = PK_LOGICAL_true,
    };
    PK_BCURVE_t bcurve;
    var fault = new PK_BCURVE_fitted_fault_t();
    ParasolidXtCorpusHost.Check(PK_BCURVE_create_fitted(&options, &bcurve, &fault), "PK_BCURVE_create_fitted");
    if (fault.status != PK_BCURVE_fitted_success_c)
        throw new InvalidOperationException("fitted status was " + fault.status);
    return AddConstructionGeometry(bcurve);
}

static unsafe PK_BODY_t CreatePiecewiseBSurf()
{
    var coefficients = stackalloc double[]
    {
        0.0, 0.0, 0.0,  1.0, 0.0, 0.5,  2.0, 0.0, 0.0,
        0.0, 1.0, 0.4,  1.0, 1.0, 1.2,  2.0, 1.0, 0.3,
        0.0, 2.0, 0.0,  1.0, 2.0, 0.6,  2.0, 2.0, 0.0,
    };
    var standardForm = new PK_BSURF_piecewise_sf_t(
        2,
        2,
        1,
        1,
        3,
        PK_LOGICAL_false,
        PK_piecewise_rep_bezier_c,
        coefficients);
    PK_BSURF_t bsurf;
    ParasolidXtCorpusHost.Check(PK_BSURF_create_piecewise(&standardForm, &bsurf), "PK_BSURF_create_piecewise");
    return AddConstructionGeometry(bsurf);
}

static unsafe PK_BODY_t CreateSplinewiseBSurf()
{
    var positions = stackalloc PK_VECTOR_t[]
    {
        new PK_VECTOR_t(0.0, 0.0, 0.0), new PK_VECTOR_t(1.0, 0.0, 0.5), new PK_VECTOR_t(2.0, 0.0, 0.0),
        new PK_VECTOR_t(0.0, 1.0, 0.4), new PK_VECTOR_t(1.0, 1.0, 1.2), new PK_VECTOR_t(2.0, 1.0, 0.3),
        new PK_VECTOR_t(0.0, 2.0, 0.0), new PK_VECTOR_t(1.0, 2.0, 0.6), new PK_VECTOR_t(2.0, 2.0, 0.0),
    };
    var standardForm = new PK_BSURF_splinewise_sf_t(
        2,
        2,
        3,
        3,
        positions,
        PK_PARAM_end_natural_c,
        PK_PARAM_end_natural_c,
        PK_PARAM_end_natural_c,
        PK_PARAM_end_natural_c,
        null,
        null,
        null,
        null,
        PK_PARAM_knot_auto_c,
        PK_PARAM_knot_auto_c,
        null,
        null,
        PK_PARAM_twist_no_c,
        PK_PARAM_twist_no_c,
        PK_PARAM_twist_no_c,
        PK_PARAM_twist_no_c,
        new PK_VECTOR_t(0.0, 0.0, 0.0),
        new PK_VECTOR_t(0.0, 0.0, 0.0),
        new PK_VECTOR_t(0.0, 0.0, 0.0),
        new PK_VECTOR_t(0.0, 0.0, 0.0));
    PK_BSURF_t bsurf;
    ParasolidXtCorpusHost.Check(PK_BSURF_create_splinewise(&standardForm, &bsurf), "PK_BSURF_create_splinewise");
    return AddConstructionGeometry(bsurf);
}

static unsafe PK_BODY_t AddConstructionGeometry(PK_GEOM_t geometry)
{
    PK_BODY_t body;
    ParasolidXtCorpusHost.Check(PK_BODY_create_sheet_rectangle(4.0, 3.0, null, &body), "PK_BODY_create_sheet_rectangle");
    var geometries = stackalloc PK_GEOM_t[1];
    geometries[0] = geometry;
    ParasolidXtCorpusHost.Check(PK_PART_add_geoms(body, 1, geometries), "PK_PART_add_geoms");
    return body;
}

static unsafe PK_BODY_t MakeSheetBody(PK_SURF_t surface, PK_UVBOX_t uvBox)
{
    PK_BODY_t body;
    ParasolidXtCorpusHost.Check(PK_SURF_make_sheet_body(surface, uvBox, &body), "PK_SURF_make_sheet_body");
    return body;
}
