using System.Buffers.Binary;

namespace ProjectGmKernel.Xt;

public static class XtBrepConverter
{
    public static XtBrepModel Decode(XtDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);
        var roots = XtPartGraph.GetRootIndexes(document);
        var groups = document.Nodes.GroupBy(node => Classify(document.Schema.GetNode(node.Type).Name)).ToDictionary(group => group.Key, group => group.ToArray());
        XtNode[] G(NodeGroup group) => groups.TryGetValue(group, out var nodes) ? nodes : [];
        var bodyNodes=G(NodeGroup.Body); var regionNodes=G(NodeGroup.Region); var shellNodes=G(NodeGroup.Shell); var faceNodes=G(NodeGroup.Face);
        var loopNodes=G(NodeGroup.Loop); var finNodes=G(NodeGroup.Fin); var edgeNodes=G(NodeGroup.Edge); var vertexNodes=G(NodeGroup.Vertex);
        var pointNodes=G(NodeGroup.Point); var geometryNodes=G(NodeGroup.Geometry); var assemblyNodes=G(NodeGroup.Assembly); var instanceNodes=G(NodeGroup.Instance);
        var attributeDefinitionNodes=G(NodeGroup.AttributeDefinition); var attributeNodes=G(NodeGroup.Attribute); var meshNodes=G(NodeGroup.Mesh); var latticeNodes=G(NodeGroup.Lattice); var frameNodes=G(NodeGroup.Frame); var transformNodes=G(NodeGroup.Transform);
        var chartNodes=ByName(document,"CHART");var limitNodes=ByName(document,"LIMIT");var intersectionDataNodes=ByName(document,"INTERSECTION_DATA");var geometricOwnerNodes=ByName(document,"GEOMETRIC_OWNER");var nurbsNodes=ByName(document,"NURBS_SURF").Concat(ByName(document,"NURBS_CURVE")).ToArray();var hvectorCount=chartNodes.Sum(node=>FieldValues(document,node,"hvec").Length)+limitNodes.Sum(node=>FieldValues(document,node,"hvec").Length);var intersectionScalarCount=intersectionDataNodes.Sum(node=>FieldValues(document,node,"values").Length);var splineCounts=CountSplines(document,nurbsNodes);
        var decodedDefinitions=DecodeDefinitions(document,attributeDefinitionNodes);var definitionStringCount=decodedDefinitions.Sum(static definition=>1+definition.FieldNames.Length);var definitionStringBytes=decodedDefinitions.Sum(static definition=>definition.Name.Length+definition.FieldNames.Sum(static name=>name.Length));
        var decodedAttributes=DecodeAttributes(document,attributeNodes);var attributeValueCount=decodedAttributes.Sum(static attribute=>attribute.Values.Length);var attributeValueBytes=decodedAttributes.Sum(static attribute=>attribute.Values.Sum(static value=>value.Data.Length));
        var meshScalarCount=MeshScalarCount(document,meshNodes);var meshReferenceCount=MeshReferenceCount(document,meshNodes);
        var userFieldNodes=document.Nodes.Where(static node=>node.UserFields.Length!=0).ToArray();var userFieldBytes=userFieldNodes.Sum(static node=>node.UserFields.Length*4);
        var builder = new XtBrepBuilder(new XtBrepCounts(
            Parts: bodyNodes.Length+assemblyNodes.Length, Bodies: bodyNodes.Length, Regions: regionNodes.Length, Shells: shellNodes.Length,
            Faces: faceNodes.Length, Loops: loopNodes.Length, Fins: finNodes.Length, Edges: edgeNodes.Length,
            Vertices: vertexNodes.Length, Points: pointNodes.Length, Geometries: geometryNodes.Length,
            Transforms: transformNodes.Length, Frames: frameNodes.Length, Assemblies: assemblyNodes.Length,
            Instances: instanceNodes.Length, AttributeDefinitions: attributeDefinitionNodes.Length,AttributeFieldDefinitions:attributeDefinitionNodes.Sum(static node=>Math.Max(0,node.VariableLength)),
            Attributes: attributeNodes.Length,AttributeValues:attributeValueCount, UserFields:userFieldNodes.Length, Meshes: meshNodes.Length, Lattices: latticeNodes.Length,Connections:meshReferenceCount,ControlPoints:splineCounts.ControlPoints,Scalars:intersectionScalarCount+splineCounts.Scalars+meshScalarCount,Charts:chartNodes.Length,Limits:limitNodes.Length,IntersectionData:intersectionDataNodes.Length,HVectors:hvectorCount,GeometricOwners:geometricOwnerNodes.Length,TransmitOrder:document.Nodes.Length,Strings:definitionStringCount,PayloadBytes:userFieldBytes+attributeValueBytes+definitionStringBytes));
        builder.VersionText = document.VersionText;

        var bodies=Map(bodyNodes); var regions=Map(regionNodes); var shells=Map(shellNodes); var faces=Map(faceNodes); var loops=Map(loopNodes);
        var fins=Map(finNodes); var edges=Map(edgeNodes); var vertices=Map(vertexNodes); var points=Map(pointNodes); var geometries=Map(geometryNodes);
        var assemblies=Map(assemblyNodes); var instances=Map(instanceNodes); var transforms=Map(transformNodes);var frames=Map(frameNodes);var meshes=Map(meshNodes);var lattices=Map(latticeNodes);var charts=Map(chartNodes);var limits=Map(limitNodes);var intersectionData=Map(intersectionDataNodes);var geometricOwners=Map(geometricOwnerNodes);var parts=new Dictionary<XtNodeIndex,XtPartIndex>();

        var rootSet=roots.ToHashSet();
        for(var i=0;i<bodyNodes.Length;i++)parts.Add(bodyNodes[i].Index,i);for(var i=0;i<assemblyNodes.Length;i++)parts.Add(assemblyNodes[i].Index,bodyNodes.Length+i);
        for(var i=0;i<bodyNodes.Length;i++){var next=Ptr(document,bodyNodes[i],"next");var previous=Ptr(document,bodyNodes[i],"previous");var externalNext=next!=0&&!parts.ContainsKey(next);var externalPrevious=previous!=0&&!parts.ContainsKey(previous);builder.Parts[i]=new XtPartRow{Kind=XtPartKind.Body,TransmitIndex=bodyNodes[i].Index,IsRoot=(byte)(rootSet.Contains(bodyNodes[i].Index)?1:0),HasExternalNext=(byte)(externalNext?1:0),HasExternalPrevious=(byte)(externalPrevious?1:0),ExternalNext=externalNext?next:0,ExternalPrevious=externalPrevious?previous:0,Body=i,Assembly=-1,Name=-1,Next=LookupKnown(parts,next),Previous=LookupKnown(parts,previous)};}
        for(var i=0;i<assemblyNodes.Length;i++){var part=bodyNodes.Length+i;var next=Ptr(document,assemblyNodes[i],"next");var previous=Ptr(document,assemblyNodes[i],"previous");var externalNext=next!=0&&!parts.ContainsKey(next);var externalPrevious=previous!=0&&!parts.ContainsKey(previous);builder.Parts[part]=new XtPartRow{Kind=XtPartKind.Assembly,TransmitIndex=assemblyNodes[i].Index,IsRoot=(byte)(rootSet.Contains(assemblyNodes[i].Index)?1:0),HasExternalNext=(byte)(externalNext?1:0),HasExternalPrevious=(byte)(externalPrevious?1:0),ExternalNext=externalNext?next:0,ExternalPrevious=externalPrevious?previous:0,Body=-1,Assembly=i,Name=-1,Next=LookupKnown(parts,next),Previous=LookupKnown(parts,previous)};}
        for (var i=0; i<bodyNodes.Length; i++) builder.Bodies[i]=new XtBodyRow { Kind=Ptr(document,bodyNodes[i],"child")!=0?XtBodyKind.Compound:BodyKind(document, bodyNodes[i]),HighestNodeId=(int)Integer(document,bodyNodes[i],"highest_node_id"),LowestNodeId=(int)Integer(document,bodyNodes[i],"lowest_node_id"),ReferenceInstance=LookupOptional(instances,Ptr(document,bodyNodes[i],"ref_instance")),Owner=LookupOptional(bodies,Ptr(document,bodyNodes[i],"owner")),Child=LookupOptional(bodies,Ptr(document,bodyNodes[i],"child")),Surface=LookupOptional(geometries,Ptr(document,bodyNodes[i],"surface")),Curve=LookupOptional(geometries,Ptr(document,bodyNodes[i],"curve")),Point=LookupOptional(points,Ptr(document,bodyNodes[i],"point")),BoundarySurface=LookupOptional(geometries,Ptr(document,bodyNodes[i],"boundary_surface")),BoundaryCurve=LookupOptional(geometries,Ptr(document,bodyNodes[i],"boundary_curve")),BoundaryPoint=LookupOptional(points,Ptr(document,bodyNodes[i],"boundary_point")),BoundaryMesh=LookupOptional(meshes,Ptr(document,bodyNodes[i],"boundary_mesh")),BoundaryPolyline=LookupOptional(meshes,Ptr(document,bodyNodes[i],"boundary_polyline")), Regions=RangeOrFirst(OwnedRange(regionNodes, bodyNodes[i].Index, document),Ptr(document,bodyNodes[i],"region"),regions), Shells=RangeOrFirst(OwnedRange(shellNodes, bodyNodes[i].Index, document),Ptr(document,bodyNodes[i],"shell"),shells), Edges=RangeOrFirst(OwnedRange(edgeNodes, bodyNodes[i].Index, document),Ptr(document,bodyNodes[i],"edge"),edges), Vertices=RangeOrFirst(OwnedRange(vertexNodes, bodyNodes[i].Index, document),Ptr(document,bodyNodes[i],"vertex"),vertices), Attributes=default };
        for (var i=0; i<regionNodes.Length; i++) builder.Regions[i]=new XtRegionRow { PersistentId=(int)Integer(document,regionNodes[i],"node_id"),TransmitIndex=regionNodes[i].Index,Body=LookupOptional(bodies, Ptr(document,regionNodes[i],"body")),OwnerBody=LookupOptional(bodies,Ptr(document,regionNodes[i],"owner")), FirstShell=LookupOptional(shells,Ptr(document,regionNodes[i],"shell")), IsSolid=(byte)(Character(document,regionNodes[i],"type")=='S'?1:0), Next=LookupOptional(regions,Ptr(document,regionNodes[i],"next")),Previous=LookupOptional(regions,Ptr(document,regionNodes[i],"previous")) };
        for (var i=0; i<shellNodes.Length; i++) builder.Shells[i]=new XtShellRow { PersistentId=(int)Integer(document,shellNodes[i],"node_id"),TransmitIndex=shellNodes[i].Index,Body=LookupOptional(bodies,Ptr(document,shellNodes[i],"body")),Region=LookupOptional(regions,Ptr(document,shellNodes[i],"region","owner")), FirstFace=LookupOptional(faces,Ptr(document,shellNodes[i],"face")),FrontFace=LookupOptional(faces,Ptr(document,shellNodes[i],"front_face")),FirstEdge=LookupOptional(edges,Ptr(document,shellNodes[i],"edge")),FirstVertex=LookupOptional(vertices,Ptr(document,shellNodes[i],"vertex")), Next=LookupOptional(shells,Ptr(document,shellNodes[i],"next")) };
        for (var i=0; i<faceNodes.Length; i++){var surfacePointer=Ptr(document,faceNodes[i],"surface");var surface=geometries.TryGetValue(surfacePointer,out var geometry)?(XtOwnerKind.Geometry,geometry):meshes.TryGetValue(surfacePointer,out var mesh)?(XtOwnerKind.Mesh,mesh):(XtOwnerKind.None,-1);builder.Faces[i]=new XtFaceRow { PersistentId=(int)Integer(document,faceNodes[i],"node_id"),TransmitIndex=faceNodes[i].Index,Shell=LookupOptional(shells,Ptr(document,faceNodes[i],"shell","owner")), FirstLoop=LookupOptional(loops,Ptr(document,faceNodes[i],"loop")), Surface=surface.Item1==XtOwnerKind.Geometry?surface.Item2:-1,SurfaceKind=surface.Item1,SurfaceEntity=surface.Item2, Next=LookupOptional(faces,Ptr(document,faceNodes[i],"next")),Previous=LookupOptional(faces,Ptr(document,faceNodes[i],"previous")),NextFront=LookupOptional(faces,Ptr(document,faceNodes[i],"next_front")),PreviousFront=LookupOptional(faces,Ptr(document,faceNodes[i],"previous_front")),NextOnSurface=LookupOptional(faces,Ptr(document,faceNodes[i],"next_on_surface")),PreviousOnSurface=LookupOptional(faces,Ptr(document,faceNodes[i],"previous_on_surface")),FrontShell=LookupOptional(shells,Ptr(document,faceNodes[i],"front_shell")), Sense=Sense(document,faceNodes[i]) };}
        for (var i=0; i<loopNodes.Length; i++) builder.Loops[i]=new XtLoopRow { PersistentId=(int)Integer(document,loopNodes[i],"node_id"),TransmitIndex=loopNodes[i].Index,Face=Lookup(faces,Ptr(document,loopNodes[i],"face","owner")), FirstFin=LookupOptional(fins,Ptr(document,loopNodes[i],"fin","halfedge")), Next=LookupOptional(loops,Ptr(document,loopNodes[i],"next")), IsOuter=(byte)(Character(document,loopNodes[i],"type")=='O'?1:0) };
        for (var i=0; i<finNodes.Length; i++){var curvePointer=Ptr(document,finNodes[i],"curve");var curve=geometries.TryGetValue(curvePointer,out var geometry)?(XtOwnerKind.Geometry,geometry):meshes.TryGetValue(curvePointer,out var mesh)?(XtOwnerKind.Mesh,mesh):(XtOwnerKind.None,-1);builder.Fins[i]=new XtFinRow { PersistentId=(int)Integer(document,finNodes[i],"node_id"),TransmitIndex=finNodes[i].Index,Loop=LookupOptional(loops,Ptr(document,finNodes[i],"loop","owner")), Edge=LookupOptional(edges,Ptr(document,finNodes[i],"edge")), Vertex=LookupOptional(vertices,Ptr(document,finNodes[i],"vertex")), Curve=curve.Item1==XtOwnerKind.Geometry?curve.Item2:-1,CurveKind=curve.Item1,CurveEntity=curve.Item2, Forward=LookupOptional(fins,Ptr(document,finNodes[i],"forward")), Backward=LookupOptional(fins,Ptr(document,finNodes[i],"backward")), Other=LookupOptional(fins,Ptr(document,finNodes[i],"other")), NextAtVertex=LookupOptional(fins,Ptr(document,finNodes[i],"next_at_vx")), Sense=Sense(document,finNodes[i]),SensePresent=(byte)(Field(document,finNodes[i],["sense"]) is {Kind:not XtFieldKind.Empty}?1:0) };}
        for (var i=0; i<edgeNodes.Length; i++)
        {
            var first=Ptr(document,edgeNodes[i],"halfedge","fin");var firstNode=Node(document,first);var other=firstNode is null?null:Node(document,Ptr(document,firstNode,"other","backward"));
            var owner=Owner(Ptr(document,edgeNodes[i],"owner"),bodies,regions,shells,faces,loops,fins,edges,vertices,points,geometries,assemblies,instances,transforms);var curvePointer=Ptr(document,edgeNodes[i],"curve");var curve=geometries.TryGetValue(curvePointer,out var geometry)?(XtOwnerKind.Geometry,geometry):meshes.TryGetValue(curvePointer,out var mesh)?(XtOwnerKind.Mesh,mesh):(XtOwnerKind.None,-1);var tolerance=Field(document,edgeNodes[i],["tolerance"]);builder.Edges[i]=new XtEdgeRow { PersistentId=(int)Integer(document,edgeNodes[i],"node_id"),TransmitIndex=edgeNodes[i].Index,Start=LookupOptional(vertices,firstNode is null?0:Ptr(document,firstNode,"vertex")), End=LookupOptional(vertices,other is null?0:Ptr(document,other,"vertex")), Curve=curve.Item1==XtOwnerKind.Geometry?curve.Item2:-1,CurveKind=curve.Item1,CurveEntity=curve.Item2, FirstFin=LookupOptional(fins,first),Next=LookupOptional(edges,Ptr(document,edgeNodes[i],"next")),Previous=LookupOptional(edges,Ptr(document,edgeNodes[i],"previous")),NextOnCurve=LookupOptional(edges,Ptr(document,edgeNodes[i],"next_on_curve")),PreviousOnCurve=LookupOptional(edges,Ptr(document,edgeNodes[i],"previous_on_curve")),Body=owner.Kind==XtOwnerKind.Body?owner.Index:-1,OwnerKind=owner.Kind,Owner=owner.Index,Tolerance=tolerance?.Real??0,TolerancePresent=(byte)(tolerance is {Kind:not XtFieldKind.Empty}?1:0) };
        }
        for (var i=0; i<vertexNodes.Length; i++) { var halfedgeIndex=Ptr(document,vertexNodes[i],"halfedge");var halfedge=Node(document,halfedgeIndex);var owner=Owner(Ptr(document,vertexNodes[i],"owner"),bodies,regions,shells,faces,loops,fins,edges,vertices,points,geometries,assemblies,instances,transforms);var tolerance=Field(document,vertexNodes[i],["tolerance"]);builder.Vertices[i]=new XtVertexRow { PersistentId=(int)Integer(document,vertexNodes[i],"node_id"),TransmitIndex=vertexNodes[i].Index,Point=LookupOptional(points,Ptr(document,vertexNodes[i],"point")),FirstFin=LookupOptional(fins,halfedgeIndex), FirstEdge=LookupOptional(edges,halfedge is null?0:Ptr(document,halfedge,"edge")),Next=LookupOptional(vertices,Ptr(document,vertexNodes[i],"next")),Previous=LookupOptional(vertices,Ptr(document,vertexNodes[i],"previous")),Body=owner.Kind==XtOwnerKind.Body?owner.Index:-1,OwnerKind=owner.Kind,Owner=owner.Index,Tolerance=tolerance?.Real??0,TolerancePresent=(byte)(tolerance is {Kind:not XtFieldKind.Empty}?1:0) }; }
        for (var i=0; i<pointNodes.Length; i++){var owner=Owner(Ptr(document,pointNodes[i],"owner"),bodies,regions,shells,faces,loops,fins,edges,vertices,points,geometries,assemblies,instances,transforms);builder.Points[i]=new XtPointRow { PersistentId=(int)Integer(document,pointNodes[i],"node_id"),TransmitIndex=pointNodes[i].Index,Position=Vector(document,pointNodes[i],"pvec","position","point","coord"),OwnerKind=owner.Kind,Owner=owner.Index,Next=LookupOptional(points,Ptr(document,pointNodes[i],"next")),Previous=LookupOptional(points,Ptr(document,pointNodes[i],"previous")) };}
        var splineScalarOffset=intersectionScalarCount;var controlPointOffset=0;
        for (var i=0; i<geometryNodes.Length; i++){var node=geometryNodes[i];var row=Geometry(document,node);var owner=Owner(Ptr(document,node,"owner"),bodies,regions,shells,faces,loops,fins,edges,vertices,points,geometries,assemblies,instances,transforms);row.OwnerKind=owner.Kind;row.Owner=owner.Index;row.Next=LookupOptional(geometries,Ptr(document,node,"next"));row.Previous=LookupOptional(geometries,Ptr(document,node,"previous"));row.GeometricOwner=LookupOptional(geometricOwners,Ptr(document,node,"geometric_owner"));var surfaces=FieldValues(document,node,"surface");row.Basis=surfaces.Length>0?LookupOptional(geometries,surfaces[0].Pointer):LookupOptional(geometries,Ptr(document,node,"blend"));row.Profile=surfaces.Length>1?LookupOptional(geometries,surfaces[1].Pointer):-1;row.Spine=LookupOptional(geometries,Ptr(document,node,"spine","curve","b_curve","basis_curve","section","profile"));row.Chart=LookupOptional(charts,Ptr(document,node,"chart"));row.StartLimit=LookupOptional(limits,Ptr(document,node,"start"));row.EndLimit=LookupOptional(limits,Ptr(document,node,"end"));row.IntersectionData=LookupOptional(intersectionData,Ptr(document,node,"intersection_data"));var range=FieldValues(document,node,"range");if(range.Length>0)row.A=range[0].Real;if(range.Length>1)row.B=range[1].Real;var weights=FieldValues(document,node,"thumb_weight");if(weights.Length>0)row.D=weights[0].Real;if(weights.Length>1)row.E=weights[1].Real;var scale=Field(document,node,["scale"]);row.Scale=scale?.Real??0;row.ScalePresent=(byte)(scale is {Kind:not XtFieldKind.Empty}?1:0);row.Subtype=Character(document,node,"blend_type","check");row.Sense=Sense(document,node);row.Flag=(byte)(Logical(document,node,"true_offset")?1:0);if(row.Kind is XtGeometryKind.BSurf or XtGeometryKind.BCurve)DecodeSpline(document,node,ref row,builder,ref controlPointOffset,ref splineScalarOffset);builder.Geometries[i]=row;}
        for(var i=0;i<geometricOwnerNodes.Length;i++){var node=geometricOwnerNodes[i];var owner=Owner(Ptr(document,node,"owner"),bodies,regions,shells,faces,loops,fins,edges,vertices,points,geometries,assemblies,instances,transforms);var shared=Owner(Ptr(document,node,"shared_geometry"),bodies,regions,shells,faces,loops,fins,edges,vertices,points,geometries,assemblies,instances,transforms);builder.GeometricOwners[i]=new XtGeometricOwnerRow{TransmitIndex=node.Index,OwnerKind=owner.Kind,Owner=owner.Index,Next=LookupOptional(geometricOwners,Ptr(document,node,"next")),Previous=LookupOptional(geometricOwners,Ptr(document,node,"previous")),SharedGeometryKind=shared.Kind,SharedGeometry=shared.Index};}
        var hvectorOffset=0;for(var i=0;i<chartNodes.Length;i++){var node=chartNodes[i];var hv=FieldValues(document,node,"hvec");var errors=FieldValues(document,node,"parameter_error");builder.Charts[i]=new XtChartRow{TransmitIndex=node.Index,BaseParameter=Real(document,node,"base_parameter"),BaseScale=Real(document,node,"base_scale"),ChartCount=(int)Integer(document,node,"chart_count"),ChordalError=Real(document,node,"chordal_error"),AngularError=Real(document,node,"angular_error"),ParameterErrorLow=errors.Length>0?errors[0].Real:0,ParameterErrorHigh=errors.Length>1?errors[1].Real:0,ParameterErrorLowPresent=(byte)(errors.Length>0&&errors[0].Kind!=XtFieldKind.Empty?1:0),ParameterErrorHighPresent=(byte)(errors.Length>1&&errors[1].Kind!=XtFieldKind.Empty?1:0),HVectors=new XtRange{Offset=hvectorOffset,Count=hv.Length}};foreach(var value in hv)builder.HVectors[hvectorOffset++]=new XtHVectorRow{X=value.Vector.X,Y=value.Vector.Y,Z=value.Vector.Z,W=value.Fourth};}
        for(var i=0;i<limitNodes.Length;i++){var node=limitNodes[i];var hv=FieldValues(document,node,"hvec");var type=Field(document,node,["type"]);var term=Field(document,node,["term_use"]);builder.Limits[i]=new XtLimitRow{TransmitIndex=node.Index,Type=type?.Character??'\0',TermUse=term?.Character??'\0',TypePresent=(byte)(type is {Kind:not XtFieldKind.Empty}?1:0),TermUsePresent=(byte)(term is {Kind:not XtFieldKind.Empty}?1:0),HVectors=new XtRange{Offset=hvectorOffset,Count=hv.Length}};foreach(var value in hv)builder.HVectors[hvectorOffset++]=new XtHVectorRow{X=value.Vector.X,Y=value.Vector.Y,Z=value.Vector.Z,W=value.Fourth};}
        var scalarOffset=0;for(var i=0;i<intersectionDataNodes.Length;i++){var node=intersectionDataNodes[i];var values=FieldValues(document,node,"values");builder.IntersectionData[i]=new XtIntersectionDataRow{TransmitIndex=node.Index,UvType=(uint)Integer(document,node,"uv_type"),Values=new XtRange{Offset=scalarOffset,Count=values.Length}};foreach(var value in values)builder.Scalars[scalarOffset++]=new XtScalarRow{Value=value.Real,Present=(byte)(value.Kind==XtFieldKind.Empty?0:1)};}
        for (var i=0; i<assemblyNodes.Length; i++) builder.Assemblies[i]=new XtAssemblyRow {HighestNodeId=(int)Integer(document,assemblyNodes[i],"highest_node_id"), Instances=OwnedRange(instanceNodes,assemblyNodes[i].Index,document), Attributes=default, Name=-1,ReferenceInstance=LookupOptional(instances,Ptr(document,assemblyNodes[i],"ref_instance")),Next=-1,Previous=-1 };
        for (var i=0; i<instanceNodes.Length; i++){var partPointer=Ptr(document,instanceNodes[i],"part");var nip=Ptr(document,instanceNodes[i],"next_in_part");var pip=Ptr(document,instanceNodes[i],"prev_in_part");var nop=Ptr(document,instanceNodes[i],"next_of_part");var pop=Ptr(document,instanceNodes[i],"prev_of_part");builder.Instances[i]=new XtInstanceRow { TransmitIndex=instanceNodes[i].Index,Owner=Lookup(assemblies,Ptr(document,instanceNodes[i],"assembly","owner")), Part=LookupKnown(parts,partPointer),HasExternalPart=(byte)(partPointer!=0&&!parts.ContainsKey(partPointer)?1:0),ExternalLinks=(byte)((nip!=0&&!instances.ContainsKey(nip)?1:0)|(pip!=0&&!instances.ContainsKey(pip)?2:0)|(nop!=0&&!instances.ContainsKey(nop)?4:0)|(pop!=0&&!instances.ContainsKey(pop)?8:0)), Transform=LookupOptional(transforms,Ptr(document,instanceNodes[i],"transform")),NextInPart=LookupKnown(instances,nip),PreviousInPart=LookupKnown(instances,pip),NextOfPart=LookupKnown(instances,nop),PreviousOfPart=LookupKnown(instances,pop), Attributes=default };}
        for (var i=0; i<transformNodes.Length; i++){var row=Transform(document,transformNodes[i]);row.Owner=LookupOptional(instances,Ptr(document,transformNodes[i],"owner"));builder.Transforms[i]=row;}
        for(var i=0;i<frameNodes.Length;i++){var node=frameNodes[i];var geometryPointer=Ptr(document,node,"geometry");var geometry=geometries.TryGetValue(geometryPointer,out var geometryIndex)?(XtOwnerKind.Geometry,geometryIndex):meshes.TryGetValue(geometryPointer,out var meshIndex)?(XtOwnerKind.Mesh,meshIndex):(XtOwnerKind.None,-1);var owner=Owner(Ptr(document,node,"owner"),bodies,regions,shells,faces,loops,fins,edges,vertices,points,geometries,assemblies,instances,transforms,frames);builder.Frames[i]=new XtFrameRow{PersistentId=(int)Integer(document,node,"node_id"),TransmitIndex=node.Index,Geometry=geometry.Item1==XtOwnerKind.Geometry?geometry.Item2:-1,GeometryKind=geometry.Item1,GeometryEntity=geometry.Item2,Next=LookupOptional(frames,Ptr(document,node,"next")),Previous=LookupOptional(frames,Ptr(document,node,"previous")),NextOnGeometry=LookupOptional(frames,Ptr(document,node,"next_on_geometry")),PreviousOnGeometry=LookupOptional(frames,Ptr(document,node,"previous_on_geometry")),OwnerKind=owner.Kind,Owner=owner.Index,Sense=Sense(document,node)};}
        var definitionMap=Map(attributeDefinitionNodes);var fieldDefinitionOffset=0;
        for (var i=0; i<attributeDefinitionNodes.Length; i++)
        {
            var node=attributeDefinitionNodes[i];var actions=FieldValues(document,node,"actions");var owners=FieldValues(document,node,"legal_owners");ulong actionValues=0;ulong ownerBits=0;for(var j=0;j<actions.Length&&j<8;j++)actionValues|=(ulong)(byte)actions[j].Integer<<(j*8);for(var j=0;j<owners.Length&&j<64;j++)if(owners[j].Integer!=0)ownerBits|=1ul<<j;
            var count=Math.Max(Math.Max(0,node.VariableLength),decodedDefinitions[i].FieldNames.Length);builder.AttributeDefinitions[i]=new XtAttributeDefinitionRow { TransmitIndex=node.Index,Name=-1,FieldDefinitions=new XtRange{Offset=fieldDefinitionOffset,Count=count},Actions=actionValues,LegalOwners=ownerBits,TypeId=(int)Integer(document,node,"type_id") };
            for(var j=0;j<count;j++)builder.AttributeFieldDefinitions[fieldDefinitionOffset+j]=new XtAttributeFieldDefinitionRow{Name=-1,Kind=XtAttributeValueKind.Empty,Cardinality=0};fieldDefinitionOffset+=count;
        }
        var attributeValueOffset=0;var payloadOffset=0;
        for (var i=0; i<decodedAttributes.Length; i++)
        {
            var decoded=decodedAttributes[i];var owner=Owner(decoded.Owner,bodies,regions,shells,faces,loops,fins,edges,vertices,points,geometries,assemblies,instances,transforms);builder.Attributes[i]=new XtAttributeRow { TransmitIndex=attributeNodes[i].Index,Definition=LookupOptional(definitionMap,decoded.Definition),OwnerKind=owner.Kind,Owner=owner.Index,Values=new XtRange{Offset=attributeValueOffset,Count=decoded.Values.Length} };
            for(var j=0;j<decoded.Values.Length;j++)
            {
                var value=decoded.Values[j];value.Data.CopyTo(builder.Payload.Slice(payloadOffset));builder.AttributeValues[attributeValueOffset]=new XtAttributeValueRow{Kind=value.Kind,Data=new XtRange{Offset=payloadOffset,Count=value.Data.Length},Present=1};
                if(builder.Attributes[i].Definition>=0){var def=builder.AttributeDefinitions[builder.Attributes[i].Definition];if(j<def.FieldDefinitions.Count){ref var field=ref builder.AttributeFieldDefinitions[def.FieldDefinitions.Offset+j];field.Kind=value.Kind;field.Cardinality=value.Cardinality;}}
                payloadOffset+=value.Data.Length;attributeValueOffset++;
            }
        }
        var meshScalarOffset=intersectionScalarCount+splineCounts.Scalars;var meshReferenceOffset=0;
        for (var i=0; i<meshNodes.Length; i++)
        {
            var node=meshNodes[i];var ownerPointer=Ptr(document,node,"owner");var owner=meshes.TryGetValue(ownerPointer,out var ownerMesh)?(XtOwnerKind.Mesh,ownerMesh):Owner(ownerPointer,bodies,regions,shells,faces,loops,fins,edges,vertices,points,geometries,assemblies,instances,transforms);var values=FieldValues(document,node,"values");var valueRange=new XtRange{Offset=meshScalarOffset,Count=0};var kind=MeshKind(document.Schema.GetNode(node.Type).Name);foreach(var value in values){if(kind==XtMeshKind.PointValues){builder.Scalars[meshScalarOffset++]=new XtScalarRow{Value=value.Vector.X,Present=(byte)(value.Kind==XtFieldKind.Empty?0:1)};builder.Scalars[meshScalarOffset++]=new XtScalarRow{Value=value.Vector.Y,Present=(byte)(value.Kind==XtFieldKind.Empty?0:1)};builder.Scalars[meshScalarOffset++]=new XtScalarRow{Value=value.Vector.Z,Present=(byte)(value.Kind==XtFieldKind.Empty?0:1)};valueRange.Count+=3;}else{builder.Scalars[meshScalarOffset++]=new XtScalarRow{Value=value.Kind==XtFieldKind.Real?value.Real:value.Integer,Present=(byte)(value.Kind==XtFieldKind.Empty?0:1)};valueRange.Count++;}}
            builder.Meshes[i]=new XtMeshRow {Kind=kind,PersistentId=(int)Integer(document,node,"node_id"),TransmitIndex=node.Index,OwnerKind=owner.Item1,Owner=owner.Item2,Next=LookupKnown(meshes,Ptr(document,node,"next")),Previous=LookupKnown(meshes,Ptr(document,node,"previous")),Data=LookupKnown(meshes,Ptr(document,node,"data")),PsmMesh=LookupKnown(meshes,Ptr(document,node,"psm_imesh")),PositionPool=LookupKnown(meshes,Ptr(document,node,"position_pool","pvec")),NormalPool=LookupKnown(meshes,Ptr(document,node,"normal_pool")),PositionIndices=LookupKnown(meshes,Ptr(document,node,"position_indices")),NormalIndices=LookupKnown(meshes,Ptr(document,node,"normal_indices")),References=MeshReferences(document,node,meshes,builder,ref meshReferenceOffset),Values=valueRange,Sense=Character(document,node,"sense"),Token=(uint)Integer(document,node,"precision","encoding"),Token2=(uint)Integer(document,node,"normal_type"),I0=(int)Integer(document,node,"n_pvecs","n_integers","n_vectors"),I1=(int)Integer(document,node,"n_max_integers","n_max_vectors"),I2=(int)Integer(document,node,"n_bits_per_integer","shift"),I3=(int)Integer(document,node,"shift"),I4=(int)Integer(document,node,"rcv_index"),D0=Real(document,node,"base_parm"),Logical=(byte)(Logical(document,node,"closed")?1:0)};
        }
        for (var i=0; i<latticeNodes.Length; i++) builder.Lattices[i]=new XtLatticeRow { OwnerKind=XtOwnerKind.None, Owner=-1 };
        var stringIndex=0;
        for(var i=0;i<decodedDefinitions.Length;i++)
        {
            ref var definition=ref builder.AttributeDefinitions[i];definition.Name=stringIndex;WriteString(decodedDefinitions[i].Name,builder.Strings,builder.Payload,ref stringIndex,ref payloadOffset);
            for(var j=0;j<decodedDefinitions[i].FieldNames.Length;j++){builder.AttributeFieldDefinitions[definition.FieldDefinitions.Offset+j].Name=stringIndex;WriteString(decodedDefinitions[i].FieldNames[j],builder.Strings,builder.Payload,ref stringIndex,ref payloadOffset);}
        }
        for(var i=0;i<userFieldNodes.Length;i++)
        {
            var node=userFieldNodes[i];var owner=Owner(node.Index,bodies,regions,shells,faces,loops,fins,edges,vertices,points,geometries,assemblies,instances,transforms);
            builder.UserFields[i]=new XtUserFieldRow{OwnerKind=owner.Kind,Owner=owner.Index,Payload=new XtRange{Offset=payloadOffset,Count=node.UserFields.Length*4}};
            foreach(var value in node.UserFields){BinaryPrimitives.WriteInt32LittleEndian(builder.Payload.Slice(payloadOffset,4),value);payloadOffset+=4;}
        }
        for(var i=0;i<document.Nodes.Length;i++)builder.TransmitOrder[i]=new XtTransmitOrderRow{NodeIndex=document.Nodes[i].Index,Order=i};
        return builder.FinalizeModel();
    }

    public static XtDocument Encode(XtSchemaCatalog catalog, XtBrepModel model, string targetSchemaIdentity)
    {
        ArgumentNullException.ThrowIfNull(catalog); ArgumentNullException.ThrowIfNull(model);
        XtBrepValidator.ValidateRepresentable(catalog, model, targetSchemaIdentity);
        return XtBrepEncoder.Encode(catalog.Resolve(targetSchemaIdentity), model, targetSchemaIdentity);
    }

    public static bool TryDecode(XtDocument document, out XtBrepModel? model, out XtDiagnostic diagnostic)
    {
        try { model=Decode(document); diagnostic=default; return true; }
        catch (Exception exception) when (exception is XtFormatException or FormatException) { model=null; diagnostic=new XtDiagnostic(exception is XtFormatException f?f.Code:XtErrorCode.ModelInvalid,exception.Message); return false; }
    }

    public static bool TryEncode(XtSchemaCatalog catalog,XtBrepModel model,string targetSchemaIdentity,out XtDocument? document,out XtDiagnostic diagnostic)
    {
        try{document=Encode(catalog,model,targetSchemaIdentity);diagnostic=default;return true;}
        catch(Exception exception) when(exception is XtFormatException or FormatException or NotSupportedException or ArgumentException){document=null;diagnostic=new XtDiagnostic(exception is XtFormatException format?format.Code:XtErrorCode.NotRepresentable,exception.Message);return false;}
    }

    private static Dictionary<XtNodeIndex,XtTableIndex> Map(XtNode[] nodes) => nodes.Select((node,index)=>(node,index)).ToDictionary(x=>x.node.Index,x=>x.index);
    private static XtTableIndex Lookup(Dictionary<XtNodeIndex,XtTableIndex> map, XtNodeIndex node) => map.TryGetValue(node,out var index)?index:throw new XtFormatException(XtErrorCode.ModelInvalid,$"Missing XT node reference {node}.");
    private static XtTableIndex LookupOptional(Dictionary<XtNodeIndex,XtTableIndex> map, XtNodeIndex node) => node==0?-1:Lookup(map,node);
    private static XtTableIndex LookupKnown(Dictionary<XtNodeIndex,XtTableIndex> map,XtNodeIndex node)=>node!=0&&map.TryGetValue(node,out var index)?index:-1;
    private static XtNode? Node(XtDocument document,XtNodeIndex index){if(index==0)return null;foreach(var node in document.Nodes)if(node.Index==index)return node;return null;}
    private static XtNode[] ByName(XtDocument document,string name)=>document.Nodes.Where(node=>document.Schema.GetNode(node.Type).Name==name).ToArray();
    private static (XtOwnerKind Kind,XtTableIndex Index) Owner(XtNodeIndex node,params Dictionary<XtNodeIndex,XtTableIndex>[] maps)
    {
        var kinds=new[]{XtOwnerKind.Body,XtOwnerKind.Region,XtOwnerKind.Shell,XtOwnerKind.Face,XtOwnerKind.Loop,XtOwnerKind.Fin,XtOwnerKind.Edge,XtOwnerKind.Vertex,XtOwnerKind.Point,XtOwnerKind.Geometry,XtOwnerKind.Assembly,XtOwnerKind.Instance,XtOwnerKind.Transform,XtOwnerKind.Frame};
        for(var i=0;i<maps.Length;i++)if(maps[i].TryGetValue(node,out var index))return(kinds[i],index);
        return(XtOwnerKind.None,-1);
    }
    private static XtRange OwnedRange(XtNode[] nodes,XtNodeIndex owner,XtDocument d) { var indexes=nodes.Select((n,i)=>(n,i)).Where(x=>Ptr(d,x.n,"owner","body","region","shell","face","loop","assembly")==owner).Select(x=>x.i).ToArray(); if(indexes.Length==0)return default; for(var i=1;i<indexes.Length;i++)if(indexes[i]!=indexes[0]+i)return default; return new XtRange{Offset=indexes[0],Count=indexes.Length}; }
    private static XtRange RangeOrFirst(XtRange range,XtNodeIndex first,Dictionary<XtNodeIndex,XtTableIndex> map)=>range.Count!=0?range:first!=0&&map.TryGetValue(first,out var index)?new XtRange{Offset=index,Count=1}:default;
    private static XtTableCount MeshScalarCount(XtDocument document,XtNode[] nodes){var count=0;foreach(var node in nodes){var values=FieldValues(document,node,"values");count+=document.Schema.GetNode(node.Type).Name=="POINT_VALUES"?values.Length*3:values.Length;}return count;}
    private static XtTableCount MeshReferenceCount(XtDocument document,XtNode[] nodes){var count=0;foreach(var node in nodes){var values=FieldValues(document,node,"teeth");if(values.Length==0)values=FieldValues(document,node,"combs");count+=values.Length;}return count;}
    private static XtRange MeshReferences(XtDocument document,XtNode node,Dictionary<XtNodeIndex,XtTableIndex> map,XtBrepBuilder builder,ref XtTableOffset offset){var values=FieldValues(document,node,"teeth");if(values.Length==0)values=FieldValues(document,node,"combs");var range=new XtRange{Offset=offset,Count=values.Length};foreach(var value in values)builder.Connections[offset++]=new XtConnectionRow{A=LookupKnown(map,value.Pointer),B=-1,C=-1,D=-1,Next=-1};return range;}

    private static XtBodyKind BodyKind(XtDocument d,XtNode n) => Integer(d,n,"type","body_type") switch { 1=>XtBodyKind.Solid,2=>XtBodyKind.Sheet,3=>XtBodyKind.Wire,4=>XtBodyKind.Minimum,5=>XtBodyKind.General,6=>XtBodyKind.Empty,7=>XtBodyKind.Compound,_=>XtBodyKind.Unspecified };
    private static XtGeometryRow Geometry(XtDocument d,XtNode n)
    {
        var name=d.Schema.GetNode(n.Type).Name; var row=new XtGeometryRow { Kind=GeometryKind(name),PersistentId=(int)Integer(d,n,"node_id"),TransmitIndex=n.Index, Origin=Vector(d,n,"pvec","point","centre","origin","point_1","base"), Axis=Vector(d,n,"axis","normal","direction","point_2"), Reference=Vector(d,n,"x_axis","ref_direction","sweep"), A=Real(d,n,"radius","major_radius","offset","parm_1"), B=Real(d,n,"minor_radius","sin_half_angle","parm_2"),C=Real(d,n,"cos_half_angle"), Basis=-1, Profile=-1,Spine=-1,Chart=-1,StartLimit=-1,EndLimit=-1,IntersectionData=-1,GeometricOwner=-1,Owner=-1,Next=-1,Previous=-1 };if(row.Kind==XtGeometryKind.BlendBound)row.A=Integer(d,n,"boundary");
        return row;
    }
    private static (XtTableCount ControlPoints,XtTableCount Scalars) CountSplines(XtDocument document,XtNode[] nurbsNodes)
    {
        var controls=0;var scalars=0;foreach(var nurbs in nurbsNodes){var dimension=Math.Max(1,(int)Integer(document,nurbs,"vertex_dim"));var vertices=Node(document,Ptr(document,nurbs,"bspline_vertices"));var values=vertices is null?[]:FieldValues(document,vertices,"vertices");controls+=values.Length/dimension;if(Logical(document,nurbs,"rational"))scalars+=values.Length/dimension;var curve=document.Schema.GetNode(nurbs.Type).Name=="NURBS_CURVE";var names=curve?new[]{"knots","knot_mult"}:new[]{"u_knots","v_knots","u_knot_mult","v_knot_mult"};foreach(var name in names){var node=Node(document,Ptr(document,nurbs,name));if(node is not null)scalars+=FieldValues(document,node,name.Contains("mult",StringComparison.Ordinal)?"mult":"knots").Length;}}return(controls,scalars);
    }
    private static void DecodeSpline(XtDocument document,XtNode surface,ref XtGeometryRow row,XtBrepBuilder builder,ref XtTableOffset controlOffset,ref XtTableOffset scalarOffset)
    {
        var nurbs=Node(document,Ptr(document,surface,"nurbs"));if(nurbs is null)return;var curve=document.Schema.GetNode(nurbs.Type).Name=="NURBS_CURVE";row.DegreeU=(short)Integer(document,nurbs,curve?"degree":"u_degree");row.DegreeV=curve?(short)0:(short)Integer(document,nurbs,"v_degree");row.ControlCountU=(int)Integer(document,nurbs,curve?"n_vertices":"n_u_vertices");row.ControlCountV=curve?1:(int)Integer(document,nurbs,"n_v_vertices");row.KnotTypeU=(uint)Integer(document,nurbs,curve?"knot_type":"u_knot_type");row.KnotTypeV=curve?0:(uint)Integer(document,nurbs,"v_knot_type");row.Rational=(byte)(Logical(document,nurbs,"rational")?1:0);row.PeriodicU=(byte)(Logical(document,nurbs,curve?"periodic":"u_periodic")?1:0);row.PeriodicV=curve?(byte)0:(byte)(Logical(document,nurbs,"v_periodic")?1:0);row.ClosedU=(byte)(Logical(document,nurbs,curve?"closed":"u_closed")?1:0);row.ClosedV=curve?(byte)0:(byte)(Logical(document,nurbs,"v_closed")?1:0);row.Form=(byte)Integer(document,nurbs,curve?"curve_form":"surface_form");var dimension=Math.Max(1,(int)Integer(document,nurbs,"vertex_dim"));row.VertexDimension=(short)dimension;var coordinateDimension=row.Rational!=0?dimension-1:dimension;var vertexNode=Node(document,Ptr(document,nurbs,"bspline_vertices"));var vertices=vertexNode is null?[]:FieldValues(document,vertexNode,"vertices");var count=vertices.Length/dimension;row.ControlPoints=new XtRange{Offset=controlOffset,Count=count};if(row.Rational!=0)row.Weights=new XtRange{Offset=scalarOffset,Count=count};for(var i=0;i<count;i++){builder.ControlPoints[controlOffset++]=new XtVector3{X=coordinateDimension>0?vertices[i*dimension].Real:0,Y=coordinateDimension>1?vertices[i*dimension+1].Real:0,Z=coordinateDimension>2?vertices[i*dimension+2].Real:0};if(row.Rational!=0)builder.Scalars[scalarOffset++]=new XtScalarRow{Value=vertices[i*dimension+dimension-1].Real,Present=1};}
        row.MultiplicitiesU=StoreScalars(document,Node(document,Ptr(document,nurbs,curve?"knot_mult":"u_knot_mult")),"mult",builder,ref scalarOffset);row.MultiplicitiesV=curve?default:StoreScalars(document,Node(document,Ptr(document,nurbs,"v_knot_mult")),"mult",builder,ref scalarOffset);row.KnotsU=StoreScalars(document,Node(document,Ptr(document,nurbs,curve?"knots":"u_knots")),"knots",builder,ref scalarOffset);row.KnotsV=curve?default:StoreScalars(document,Node(document,Ptr(document,nurbs,"v_knots")),"knots",builder,ref scalarOffset);
        var data=Node(document,Ptr(document,surface,"data"));if(data is null)return;if(curve){SetInterval(document,data,"tint",out row.OriginalULow,out row.OriginalUHigh);row.SelfIntersection=(byte)Integer(document,data,"self_int");row.OriginalUStart=Character(document,data,"t_start");row.OriginalUEnd=Character(document,data,"t_end");return;}SetInterval(document,data,"original_uint",out row.OriginalULow,out row.OriginalUHigh);SetInterval(document,data,"original_vint",out row.OriginalVLow,out row.OriginalVHigh);SetInterval(document,data,"extended_uint",out row.ExtendedULow,out row.ExtendedUHigh);SetInterval(document,data,"extended_vint",out row.ExtendedVLow,out row.ExtendedVHigh);row.SelfIntersection=(byte)Integer(document,data,"self_int");row.OriginalUStart=Character(document,data,"original_u_start");row.OriginalUEnd=Character(document,data,"original_u_end");row.OriginalVStart=Character(document,data,"original_v_start");row.OriginalVEnd=Character(document,data,"original_v_end");row.ExtendedUStart=Character(document,data,"extended_u_start");row.ExtendedUEnd=Character(document,data,"extended_u_end");row.ExtendedVStart=Character(document,data,"extended_v_start");row.ExtendedVEnd=Character(document,data,"extended_v_end");
    }
    private static XtRange StoreScalars(XtDocument document,XtNode? node,string field,XtBrepBuilder builder,ref XtTableOffset offset){if(node is null)return default;var values=FieldValues(document,node,field);var range=new XtRange{Offset=offset,Count=values.Length};foreach(var value in values)builder.Scalars[offset++]=new XtScalarRow{Value=value.Kind==XtFieldKind.Real?value.Real:value.Integer,Present=(byte)(value.Kind==XtFieldKind.Empty?0:1)};return range;}
    private static void SetInterval(XtDocument document,XtNode node,string name,out double low,out double high){var value=Field(document,node,[name]);low=value?.Vector.X??0;high=value?.Vector.Y??0;}
    private static XtGeometryKind GeometryKind(string n) => n switch { "LINE"=>XtGeometryKind.Line,"CIRCLE"=>XtGeometryKind.Circle,"ELLIPSE"=>XtGeometryKind.Ellipse,"INTERSECTION" or "ICURVE"=>XtGeometryKind.ICurve,"B_CURVE" or "BCURVE" or "BSPLINE_CURVE"=>XtGeometryKind.BCurve,"SP_CURVE" or "SPCURVE"=>XtGeometryKind.SPCurve,"FCURVE"=>XtGeometryKind.FCurve,"CP_CURVE" or "CPCURVE" or "CPC"=>XtGeometryKind.CPCurve,"TR_CURVE" or "TRCURVE" or "TRIMMED_CURVE"=>XtGeometryKind.TRCurve,"PLANE"=>XtGeometryKind.Plane,"CYLINDER"=>XtGeometryKind.Cylinder,"CONE"=>XtGeometryKind.Cone,"SPHERE"=>XtGeometryKind.Sphere,"TORUS"=>XtGeometryKind.Torus,"B_SURFACE" or "BSURF" or "BSPLINE_SURF"=>XtGeometryKind.BSurf,"BLEND_SURFACE" or "BLENDSF" or "BLENDED_EDGE"=>XtGeometryKind.BlendSF,"BLEND_BOUND"=>XtGeometryKind.BlendBound,"OFFSET_SURFACE" or "OFFSET_SURF"=>XtGeometryKind.Offset,"SWEPT_SURFACE" or "SWEPT_SURF"=>XtGeometryKind.Swept,"SPUN_SURFACE" or "SPUN_SURF"=>XtGeometryKind.Spun,_=>XtGeometryKind.FSurf };
    private static XtTransformRow Transform(XtDocument d,XtNode n)
    {
        var matrix=FieldValues(d,n,"rotation_matrix");var translation=Vector(d,n,"translation_vector","translation","offset");
        double M(int i,double fallback)=>i<matrix.Length?matrix[i].Real:fallback;
        return new(){TransmitIndex=n.Index,M00=M(0,1),M01=M(1,0),M02=M(2,0),M03=translation.X,M10=M(3,0),M11=M(4,1),M12=M(5,0),M13=translation.Y,M20=M(6,0),M21=M(7,0),M22=M(8,1),M23=translation.Z,Owner=-1,Scale=Real(d,n,"scale"),Flag=(int)Integer(d,n,"flag")};
    }
    private static sbyte Sense(XtDocument d,XtNode n) => Character(d,n,"sense")=='-'?(sbyte)-1:(sbyte)1;

    private static XtNodeIndex Ptr(XtDocument d,XtNode n,params string[] names) { var v=Field(d,n,names); return v?.Pointer??0; }
    private static long Integer(XtDocument d,XtNode n,params string[] names) { var v=Field(d,n,names); return v?.Integer??0; }
    private static bool Logical(XtDocument d,XtNode n,params string[] names) => Integer(d,n,names)!=0;
    private static char Character(XtDocument d,XtNode n,params string[] names){var v=Field(d,n,names);return v?.Character??'\0';}
    private static double Real(XtDocument d,XtNode n,params string[] names) { var v=Field(d,n,names); return v?.Real??0; }
    private static double RealAt(XtDocument d,XtNode n,XtFieldIndex index,double fallback) => (uint)index<(uint)n.Fields.Length?n.Fields[index].Real:fallback;
    private static XtVector3 Vector(XtDocument d,XtNode n,params string[] names) { var v=Field(d,n,names); return v is { } x?new XtVector3{X=x.Vector.X,Y=x.Vector.Y,Z=x.Vector.Z}:default; }
    private static XtFieldValue? Field(XtDocument d,XtNode n,string[] names)
    {
        var descriptor=d.Schema.GetNode(n.Type); var offset=0;
        foreach(var field in d.Schema.GetFields(descriptor))
        {
            if(!field.Transmit)continue;
            var count=field.ElementCount>1?field.ElementCount:descriptor.Variable&&field.ElementCount==1?Math.Max(0,n.VariableLength):1;
            if(names.Contains(field.Name,StringComparer.OrdinalIgnoreCase)&&count>0&&offset<n.Fields.Length)return n.Fields[offset];
            offset+=count;
        }
        return null;
    }
    private static XtFieldValue[] FieldValues(XtDocument d,XtNode n,string name)
    {
        var descriptor=d.Schema.GetNode(n.Type);var offset=0;foreach(var field in d.Schema.GetFields(descriptor)){if(!field.Transmit)continue;var count=field.ElementCount>1?field.ElementCount:descriptor.Variable&&field.ElementCount==1?Math.Max(0,n.VariableLength):1;if(field.Name==name)return n.Fields.AsSpan(offset,count).ToArray();offset+=count;}return[];
    }
    private static XtMeshKind MeshKind(string name)=>name switch{"PLINE"=>XtMeshKind.Pline,"MTOPOL"=>XtMeshKind.MTopol,"MFACET"=>XtMeshKind.MFacet,"MFIN"=>XtMeshKind.MFin,"MVERTEX"=>XtMeshKind.MVertex,"POLYLINE"=>XtMeshKind.Pline,"POLYLINE_DATA"=>XtMeshKind.PolylineData,"PSM_MESH"=>XtMeshKind.PsmMesh,"INTEGER_COMB"=>XtMeshKind.IntegerComb,"INTEGER_TOOTH"=>XtMeshKind.IntegerTooth,"VECTOR_COMB"=>XtMeshKind.VectorComb,"VECTOR_TOOTH"=>XtMeshKind.VectorTooth,"POINT_VALUES"=>XtMeshKind.PointValues,_=>XtMeshKind.Mesh};
    private static NodeGroup Classify(string n) => n switch { "NURBS_SURF" or "SURFACE_DATA" or "NURBS_CURVE" or "CURVE_DATA"=>NodeGroup.Other,"BODY"=>NodeGroup.Body,"REGION"=>NodeGroup.Region,"SHELL"=>NodeGroup.Shell,"FACE"=>NodeGroup.Face,"LOOP"=>NodeGroup.Loop,"FIN" or "HALFEDGE"=>NodeGroup.Fin,"EDGE"=>NodeGroup.Edge,"VERTEX"=>NodeGroup.Vertex,"POINT"=>NodeGroup.Point,"ASSEMBLY"=>NodeGroup.Assembly,"INSTANCE"=>NodeGroup.Instance,"TRANSFORM"=>NodeGroup.Transform,"FRAME"=>NodeGroup.Frame,"ATTRIB_DEF"=>NodeGroup.AttributeDefinition,"ATTRIBUTE"=>NodeGroup.Attribute,"MESH" or "PLINE" or "MTOPOL" or "MFACET" or "MFIN" or "MVERTEX" or "POLYLINE" or "POLYLINE_DATA" or "PSM_MESH" or "INTEGER_COMB" or "INTEGER_TOOTH" or "VECTOR_COMB" or "VECTOR_TOOTH" or "POINT_VALUES"=>NodeGroup.Mesh,"LATTICE"=>NodeGroup.Lattice,_ when n.StartsWith("BLEND",StringComparison.Ordinal)=>NodeGroup.Geometry,_ when n.Contains("CURVE",StringComparison.Ordinal)||n is "LINE" or "CIRCLE" or "ELLIPSE" or "PARACURVE" or "INTERSECTION" or "SILHOUETTE" or "CPC"=>NodeGroup.Geometry,_ when n.Contains("SURF",StringComparison.Ordinal)||n is "PLANE" or "CYLINDER" or "CONE" or "SPHERE" or "TORUS" or "PIPE" or "CPS" or "BLENDSF" or "FSURF"=>NodeGroup.Geometry,_=>NodeGroup.Other };
    private enum NodeGroup : byte { Other,Body,Region,Shell,Face,Loop,Fin,Edge,Vertex,Point,Geometry,Assembly,Instance,Transform,Frame,AttributeDefinition,Attribute,Mesh,Lattice }

    private static DecodedAttribute[] DecodeAttributes(XtDocument document,XtNode[] nodes)
    {
        var result=new DecodedAttribute[nodes.Length];for(var i=0;i<nodes.Length;i++){var pointers=FieldValues(document,nodes[i],"fields");var values=new DecodedValue[pointers.Length];for(var j=0;j<pointers.Length;j++)values[j]=DecodeValue(document,Node(document,pointers[j].Pointer));result[i]=new DecodedAttribute(Ptr(document,nodes[i],"definition"),Ptr(document,nodes[i],"owner"),values);}return result;
    }
    private static DecodedDefinition[] DecodeDefinitions(XtDocument document,XtNode[] nodes)
    {
        var result=new DecodedDefinition[nodes.Length];for(var i=0;i<nodes.Length;i++){var identifier=Node(document,Ptr(document,nodes[i],"identifier"));var fieldNamesNode=Node(document,Ptr(document,nodes[i],"field_names"));var name=ReadString(document,identifier,"string");var namePointers=fieldNamesNode is null?[]:FieldValues(document,fieldNamesNode,"names");var names=new byte[namePointers.Length][];for(var j=0;j<names.Length;j++)names[j]=ReadString(document,Node(document,namePointers[j].Pointer),"values");result[i]=new DecodedDefinition(name,names);}return result;
    }
    private static byte[] ReadString(XtDocument document,XtNode? node,string field){if(node is null)return[];var values=FieldValues(document,node,field);var bytes=new byte[values.Length];for(var i=0;i<bytes.Length;i++)bytes[i]=(byte)values[i].Character;return bytes;}
    private static void WriteString(byte[] value,Span<XtStringRow> strings,Span<byte> payload,ref XtStringIndex index,ref XtBlobOffset offset){strings[index]=new XtStringRow{Offset=offset,ByteCount=value.Length};value.CopyTo(payload.Slice(offset));offset+=value.Length;index++;}
    private static DecodedValue DecodeValue(XtDocument document,XtNode? node)
    {
        if(node is null)return new(XtAttributeValueKind.Empty,[],0);var name=document.Schema.GetNode(node.Type).Name;var values=FieldValues(document,node,"values");var kind=name switch{"INT_VALUES" or "SHORT_VALUES"=>XtAttributeValueKind.Integer,"REAL_VALUES" or "PARM_VALUES"=>XtAttributeValueKind.Real,"CHAR_VALUES"=>XtAttributeValueKind.Utf8String,"UNICODE_VALUES"=>XtAttributeValueKind.UnicodeString,"POINT_VALUES"=>XtAttributeValueKind.Coordinate,"VECTOR_VALUES"=>XtAttributeValueKind.Vector,"DIRECTION_VALUES"=>XtAttributeValueKind.Direction,"AXIS_VALUES"=>XtAttributeValueKind.Axis,"TAG_VALUES"=>XtAttributeValueKind.Entity,"POINTER_VALUES"=>XtAttributeValueKind.Pointer,_=>XtAttributeValueKind.Bytes};
        var width=kind switch{XtAttributeValueKind.Integer or XtAttributeValueKind.Real or XtAttributeValueKind.Entity or XtAttributeValueKind.Pointer=>8,XtAttributeValueKind.Coordinate or XtAttributeValueKind.Vector or XtAttributeValueKind.Direction or XtAttributeValueKind.Axis=>24,_=>1};var data=new byte[values.Length*width];
        for(var i=0;i<values.Length;i++){var span=data.AsSpan(i*width,width);if(width==8){if(kind==XtAttributeValueKind.Real)BinaryPrimitives.WriteInt64LittleEndian(span,BitConverter.DoubleToInt64Bits(values[i].Real));else BinaryPrimitives.WriteInt64LittleEndian(span,values[i].Integer!=0?values[i].Integer:values[i].Pointer);}else if(width==24){BinaryPrimitives.WriteInt64LittleEndian(span,BitConverter.DoubleToInt64Bits(values[i].Vector.X));BinaryPrimitives.WriteInt64LittleEndian(span[8..],BitConverter.DoubleToInt64Bits(values[i].Vector.Y));BinaryPrimitives.WriteInt64LittleEndian(span[16..],BitConverter.DoubleToInt64Bits(values[i].Vector.Z));}else data[i]=(byte)values[i].Character;}
        return new(kind,data,values.Length);
    }
    private readonly record struct DecodedAttribute(XtNodeIndex Definition,XtNodeIndex Owner,DecodedValue[] Values);
    private readonly record struct DecodedValue(XtAttributeValueKind Kind,byte[] Data,XtTableCount Cardinality);
    private readonly record struct DecodedDefinition(byte[] Name,byte[][] FieldNames);
}
