#!/usr/bin/env dotnet run
// Generates complete XT schema metadata for the locked project schema.
//
// Usage:
//   dotnet run scripts/GenerateXtSchema.cs
//   dotnet run scripts/GenerateXtSchema.cs -- --check

using System.Runtime.CompilerServices;
using System.Text;
using System.Text.RegularExpressions;
using SchemaElementCount = System.Int32;
using SchemaFieldCount = System.Int32;
using SchemaNodeClass = System.Int32;
using SchemaNodeType = System.Int32;

static string GetScriptPath([CallerFilePath] string path = "") => path;

var scriptDir = Path.GetDirectoryName(GetScriptPath()) ?? ".";
var repoRoot = Path.GetFullPath(Path.Combine(scriptDir, ".."));
var schemaPath = Path.Combine(repoRoot, "third_party", "parasolid", "schema", "sch_37102.sch_txt");
var outputPath = Path.Combine(repoRoot, "src", "ProjectGmKernel.Native", "Generated", "XtSchema.generated.cs");
var check = args.Contains("--check", StringComparer.Ordinal);

if (!File.Exists(schemaPath))
    throw new FileNotFoundException("Locked XT schema file is missing.", schemaPath);

var nodes = ParseSchema(schemaPath);
var generated = Generate(nodes);

if (check)
{
    if (!File.Exists(outputPath))
    {
        Console.Error.WriteLine("Generated XT schema file is missing: " + Path.GetRelativePath(repoRoot, outputPath));
        return 1;
    }

    var existing = File.ReadAllText(outputPath);
    if (!StringComparer.Ordinal.Equals(existing, generated))
    {
        Console.Error.WriteLine("Generated XT schema file is out of date. Run dotnet run scripts/GenerateXtSchema.cs.");
        return 1;
    }

    Console.WriteLine("XT schema generated file is up to date.");
    return 0;
}

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, generated, new UTF8Encoding(false));
Console.WriteLine("Generated " + Path.GetRelativePath(repoRoot, outputPath));
return 0;

static string Generate(SchemaNode[] nodes)
{
    var fields = nodes.SelectMany(node => node.Fields).ToArray();
    var sb = new StringBuilder(1 << 20);
    sb.AppendLine("// <auto-generated />");
    sb.AppendLine("// Generated from third_party/parasolid/schema/sch_37102.sch_txt.");
    sb.AppendLine("using ProjectGmKernel.Native.Runtime;");
    sb.AppendLine();
    sb.AppendLine("namespace ProjectGmKernel.Native.Generated;");
    sb.AppendLine();
    sb.AppendLine("internal static partial class XtSchema");
    sb.AppendLine("{");
    sb.AppendLine("    public const string SchemaName = \"SCH_3701000_37102\";");
    sb.AppendLine("    public const int ModelerVersion = 3701000;");
    sb.AppendLine("    public const int SchemaNumber = 37102;");
    sb.AppendLine();
    sb.AppendLine("    private static readonly XtNodeDescriptor[] NodeData =");
    sb.AppendLine("    [");

    var fieldOffset = 0;
    foreach (var node in nodes.OrderBy(node => node.TypeId))
    {
        sb.Append("        new(")
          .Append(node.TypeId).Append(", \"").Append(Escape(node.Name)).Append("\", \"").Append(Escape(node.Description)).Append("\", ")
          .Append(Bool(node.Transmit)).Append(", ").Append(node.FieldCount).Append(", ").Append(Bool(node.Variable)).Append(", ")
          .Append(fieldOffset).Append(", ").Append(node.Fields.Length).AppendLine("),");
        fieldOffset += node.Fields.Length;
    }

    sb.AppendLine("    ];");
    sb.AppendLine();
    sb.AppendLine("    private static readonly XtFieldDescriptor[] FieldData =");
    sb.AppendLine("    [");

    foreach (var node in nodes.OrderBy(node => node.TypeId))
    {
        foreach (var field in node.Fields)
        {
            sb.Append("        new(")
              .Append(node.TypeId).Append(", \"").Append(Escape(field.Name)).Append("\", '").Append(field.Type).Append("', ")
              .Append(Bool(field.Transmit)).Append(", ").Append(field.NodeClass).Append(", ").Append(field.ElementCount).AppendLine("),");
        }
    }

    sb.AppendLine("    ];");
    sb.AppendLine();
    sb.AppendLine("    public static ReadOnlySpan<XtNodeDescriptor> Nodes => NodeData;");
    sb.AppendLine("    public static ReadOnlySpan<XtFieldDescriptor> Fields => FieldData;");
    sb.AppendLine();
    sb.AppendLine("    public static XtNodeDescriptor GetNode(XtNodeType type)");
    sb.AppendLine("    {");
    sb.AppendLine("        foreach (var node in Nodes)");
    sb.AppendLine("        {");
    sb.AppendLine("            if (node.Type == type)");
    sb.AppendLine("                return node;");
    sb.AppendLine("        }");
    sb.AppendLine();
    sb.AppendLine("        return default;");
    sb.AppendLine("    }");
    sb.AppendLine("}");
    sb.AppendLine();
    sb.AppendLine("internal readonly record struct XtNodeDescriptor(");
    sb.AppendLine("    XtNodeType Type,");
    sb.AppendLine("    string Name,");
    sb.AppendLine("    string Description,");
    sb.AppendLine("    bool Transmit,");
    sb.AppendLine("    XtFieldCount FieldCount,");
    sb.AppendLine("    bool Variable,");
    sb.AppendLine("    XtFieldIndex FieldOffset,");
    sb.AppendLine("    XtFieldCount ParsedFieldCount);");
    sb.AppendLine();
    sb.AppendLine("internal readonly record struct XtFieldDescriptor(");
    sb.AppendLine("    XtNodeType OwnerType,");
    sb.AppendLine("    string Name,");
    sb.AppendLine("    char Type,");
    sb.AppendLine("    bool Transmit,");
    sb.AppendLine("    XtNodeClass NodeClass,");
    sb.AppendLine("    XtFieldElementCount ElementCount);");
    return sb.ToString();
}

static SchemaNode[] ParseSchema(string path)
{
    var nodeRegex = new Regex(@"^(?<id>\d+)\s+(?<name>[A-Z0-9_]+);\s*(?<desc>[^;]*);\s*(?<transmit>[01])\s+(?<fields>\d+)\s+(?<variable>[01])\s*$", RegexOptions.Compiled);
    var fieldRegex = new Regex(@"^(?<name>[A-Za-z0-9_]+);\s*(?<type>[A-Za-z]);\s*(?<transmit>[01])\s+(?<class>\d+)\s+(?<elements>\d+)\s*$", RegexOptions.Compiled);
    var nodes = new List<SchemaNode>();
    SchemaNodeBuilder? current = null;

    foreach (var rawLine in File.ReadLines(path))
    {
        var line = rawLine.Trim();
        if (line.Length == 0 || line.StartsWith("**", StringComparison.Ordinal) || line.StartsWith(':'))
            continue;

        var nodeMatch = nodeRegex.Match(line);
        if (nodeMatch.Success)
        {
            Flush();
            current = new SchemaNodeBuilder(
                int.Parse(nodeMatch.Groups["id"].Value),
                nodeMatch.Groups["name"].Value,
                nodeMatch.Groups["desc"].Value,
                ParseBit(nodeMatch.Groups["transmit"].Value),
                int.Parse(nodeMatch.Groups["fields"].Value),
                ParseBit(nodeMatch.Groups["variable"].Value));
            continue;
        }

        var fieldMatch = fieldRegex.Match(line);
        if (fieldMatch.Success && current is not null)
        {
            current.Fields.Add(new SchemaField(
                fieldMatch.Groups["name"].Value,
                fieldMatch.Groups["type"].Value[0],
                ParseBit(fieldMatch.Groups["transmit"].Value),
                int.Parse(fieldMatch.Groups["class"].Value),
                int.Parse(fieldMatch.Groups["elements"].Value)));
        }
    }

    Flush();
    return nodes.ToArray();

    void Flush()
    {
        if (current is null)
            return;

        if (current.Fields.Count != current.FieldCount)
            throw new FormatException($"Schema node {current.Name} declares {current.FieldCount} fields but parsed {current.Fields.Count}.");

        nodes.Add(new SchemaNode(
            current.TypeId,
            current.Name,
            current.Description,
            current.Transmit,
            current.FieldCount,
            current.Variable,
            current.Fields.ToArray()));
        current = null;
    }
}

static bool ParseBit(string value) => value switch
{
    "0" => false,
    "1" => true,
    _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Expected schema bit 0 or 1."),
};

static string Bool(bool value) => value ? "true" : "false";
static string Escape(string value) => value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);

sealed class SchemaNodeBuilder
{
    public SchemaNodeBuilder(SchemaNodeType typeId, string name, string description, bool transmit, SchemaFieldCount fieldCount, bool variable)
    {
        TypeId = typeId;
        Name = name;
        Description = description;
        Transmit = transmit;
        FieldCount = fieldCount;
        Variable = variable;
    }

    public SchemaNodeType TypeId { get; }
    public string Name { get; }
    public string Description { get; }
    public bool Transmit { get; }
    public SchemaFieldCount FieldCount { get; }
    public bool Variable { get; }
    public List<SchemaField> Fields { get; } = new();
}

readonly record struct SchemaNode(
    SchemaNodeType TypeId,
    string Name,
    string Description,
    bool Transmit,
    SchemaFieldCount FieldCount,
    bool Variable,
    SchemaField[] Fields);

readonly record struct SchemaField(
    string Name,
    char Type,
    bool Transmit,
    SchemaNodeClass NodeClass,
    SchemaElementCount ElementCount);
