#!/usr/bin/env dotnet run
// Generates complete XT schema metadata and the registry for every bundled schema.
//
// Usage:
//   dotnet run scripts/GenerateXtSchema.cs
//   dotnet run scripts/GenerateXtSchema.cs -- --check

using System.Runtime.CompilerServices;
using System.Text;
using System.Text.RegularExpressions;
using SchemaElementCount = System.Int32;
using SchemaFieldCount = System.Int32;
using SchemaNodeClass = System.Int32;
using SchemaNodeType = System.Int32;

static string GetScriptPath([CallerFilePath] string path = "") => path;

var scriptDir = Path.GetDirectoryName(GetScriptPath()) ?? ".";
var repoRoot = Path.GetFullPath(Path.Combine(scriptDir, ".."));
var schemaDir = Path.Combine(repoRoot, "third_party", "parasolid", "schema");
var schemaPath = Path.Combine(schemaDir, "sch_37102.sch_txt");
var outputPath = Path.Combine(repoRoot, "src", "ProjectGmKernel.Native", "Generated", "XtSchema.generated.cs");
var registryOutputPath = Path.Combine(repoRoot, "src", "ProjectGmKernel.Native", "Generated", "XtSchemaRegistry.generated.cs");
var check = args.Contains("--check", StringComparer.Ordinal);

if (!Directory.Exists(schemaDir) || !File.Exists(schemaPath))
    throw new FileNotFoundException("Locked XT schema file is missing.", schemaPath);

var nodes = ParseSchema(schemaPath);
var generated = Generate(nodes);
var schemas = Directory.EnumerateFiles(schemaDir, "sch_*.sch_txt", SearchOption.TopDirectoryOnly)
    .OrderBy(static path => path, StringComparer.Ordinal)
    .Select(ParseSchemaFile)
    .ToArray();
var registryGenerated = GenerateRegistry(schemas);

if (check)
{
    if (!File.Exists(outputPath) || !File.Exists(registryOutputPath))
    {
        Console.Error.WriteLine("Generated XT schema file is missing.");
        return 1;
    }

    var existing = File.ReadAllText(outputPath);
    var registryExisting = File.ReadAllText(registryOutputPath);
    if (!StringComparer.Ordinal.Equals(existing, generated) || !StringComparer.Ordinal.Equals(registryExisting, registryGenerated))
    {
        Console.Error.WriteLine("Generated XT schema file is out of date. Run dotnet run scripts/GenerateXtSchema.cs.");
        return 1;
    }

    Console.WriteLine("XT schema generated file is up to date.");
    return 0;
}

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, generated, new UTF8Encoding(false));
File.WriteAllText(registryOutputPath, registryGenerated, new UTF8Encoding(false));
Console.WriteLine("Generated " + Path.GetRelativePath(repoRoot, outputPath));
Console.WriteLine("Generated " + Path.GetRelativePath(repoRoot, registryOutputPath));
return 0;

static string GenerateRegistry(SchemaFile[] schemas)
{
    var sb = new StringBuilder(32 * 1024);
    sb.AppendLine("// <auto-generated />");
    sb.AppendLine("// Generated from every third_party/parasolid/schema/sch_*.sch_txt file.");
    sb.AppendLine("namespace ProjectGmKernel.Native.Runtime;");
    sb.AppendLine();
    sb.AppendLine("internal static partial class XtSchemaRegistry");
    sb.AppendLine("{");
    sb.AppendLine("    private static readonly XtSchemaRegistration[] RegistrationData =");
    sb.AppendLine("    [");
    foreach (var schema in schemas)
    {
        sb.Append("        new(\"").Append(Escape(schema.Identity)).Append("\", \"")
          .Append(Escape(schema.ResourceFileName)).Append("\", ")
          .Append(schema.ModelerVersion).Append(", ")
          .Append(schema.SchemaNumber).Append(", ")
          .Append(schema.Nodes.Length).Append(", ")
          .Append(schema.Nodes.Sum(static node => node.Fields.Length)).AppendLine("),");
    }
    sb.AppendLine("    ];");
    sb.AppendLine();
    sb.AppendLine("    internal static ReadOnlySpan<XtSchemaRegistration> Registrations => RegistrationData;");
    sb.AppendLine("}");
    return sb.ToString();
}

static string Generate(SchemaNode[] nodes)
{
    var fields = nodes.SelectMany(node => node.Fields).ToArray();
    var sb = new StringBuilder(1 << 20);
    sb.AppendLine("// <auto-generated />");
    sb.AppendLine("// Generated from third_party/parasolid/schema/sch_37102.sch_txt.");
    sb.AppendLine("using ProjectGmKernel.Native.Runtime;");
    sb.AppendLine();
    sb.AppendLine("namespace ProjectGmKernel.Native.Generated;");
    sb.AppendLine();
    sb.AppendLine("internal static partial class XtSchema");
    sb.AppendLine("{");
    sb.AppendLine("    public const string SchemaName = \"SCH_3701000_37102\";");
    sb.AppendLine("    public const int ModelerVersion = 3701000;");
    sb.AppendLine("    public const int SchemaNumber = 37102;");
    sb.AppendLine();
    sb.AppendLine("    private static readonly XtNodeDescriptor[] NodeData =");
    sb.AppendLine("    [");

    var fieldOffset = 0;
    foreach (var node in nodes.OrderBy(node => node.TypeId))
    {
        sb.Append("        new(")
          .Append(node.TypeId).Append(", \"").Append(Escape(node.Name)).Append("\", \"").Append(Escape(node.Description)).Append("\", ")
          .Append(Bool(node.Transmit)).Append(", ").Append(node.FieldCount).Append(", ").Append(Bool(node.Variable)).Append(", ")
          .Append(fieldOffset).Append(", ").Append(node.Fields.Length).AppendLine("),");
        fieldOffset += node.Fields.Length;
    }

    sb.AppendLine("    ];");
    sb.AppendLine();
    sb.AppendLine("    private static readonly XtFieldDescriptor[] FieldData =");
    sb.AppendLine("    [");

    foreach (var node in nodes.OrderBy(node => node.TypeId))
    {
        foreach (var field in node.Fields)
        {
            sb.Append("        new(")
              .Append(node.TypeId).Append(", \"").Append(Escape(field.Name)).Append("\", '").Append(field.Type).Append("', ")
              .Append(Bool(field.Transmit)).Append(", ").Append(field.NodeClass).Append(", ").Append(field.ElementCount).AppendLine("),");
        }
    }

    sb.AppendLine("    ];");
    sb.AppendLine();
    sb.AppendLine("    public static ReadOnlySpan<XtNodeDescriptor> Nodes => NodeData;");
    sb.AppendLine("    public static ReadOnlySpan<XtFieldDescriptor> Fields => FieldData;");
    sb.AppendLine();
    sb.AppendLine("    public static XtNodeDescriptor GetNode(XtNodeType type)");
    sb.AppendLine("    {");
    sb.AppendLine("        foreach (var node in Nodes)");
    sb.AppendLine("        {");
    sb.AppendLine("            if (node.Type == type)");
    sb.AppendLine("                return node;");
    sb.AppendLine("        }");
    sb.AppendLine();
    sb.AppendLine("        return default;");
    sb.AppendLine("    }");
    sb.AppendLine("}");
    sb.AppendLine();
    sb.AppendLine("internal readonly record struct XtNodeDescriptor(");
    sb.AppendLine("    XtNodeType Type,");
    sb.AppendLine("    string Name,");
    sb.AppendLine("    string Description,");
    sb.AppendLine("    bool Transmit,");
    sb.AppendLine("    XtFieldCount FieldCount,");
    sb.AppendLine("    bool Variable,");
    sb.AppendLine("    XtFieldIndex FieldOffset,");
    sb.AppendLine("    XtFieldCount ParsedFieldCount);");
    sb.AppendLine();
    sb.AppendLine("internal readonly record struct XtFieldDescriptor(");
    sb.AppendLine("    XtNodeType OwnerType,");
    sb.AppendLine("    string Name,");
    sb.AppendLine("    char Type,");
    sb.AppendLine("    bool Transmit,");
    sb.AppendLine("    XtNodeClass NodeClass,");
    sb.AppendLine("    XtFieldElementCount ElementCount);");
    return sb.ToString();
}

static SchemaNode[] ParseSchema(string path)
    => ParseSchemaFile(path).Nodes;

static SchemaFile ParseSchemaFile(string path)
{
    var nodeRegex = new Regex(@"^(?<id>\d+)\s+(?<name>[A-Z0-9_]+);\s*(?<desc>[^;]*);\s*(?<transmit>[01])\s+(?<fields>\d+)\s+(?<variable>[01])\s*$", RegexOptions.Compiled);
    var fieldRegex = new Regex(@"^(?<name>[A-Za-z0-9_]+);\s*(?<type>[A-Za-z]);\s*(?<transmit>[01])\s+(?<class>\d+)\s+(?<elements>\d+)\s*$", RegexOptions.Compiled);
    var nodes = new List<SchemaNode>();
    var nodeIds = new HashSet<int>();
    SchemaNodeBuilder? current = null;
    var foundStatistics = false;
    var foundTerminator = false;
    var declaredNodeCount = -1;
    var declaredFieldCount = -1;
    var declaredModelerVersion = -1;
    var identity = "";
    var lineNumber = 0;

    foreach (var rawLine in File.ReadLines(path))
    {
        lineNumber++;
        var line = rawLine.Trim();
        if (!foundStatistics)
        {
            var version = Regex.Match(line, @"modeller version\s+(?<modeler>\d+)/", RegexOptions.IgnoreCase);
            if (version.Success)
                declaredModelerVersion = int.Parse(version.Groups["modeler"].Value);
            var statistics = Regex.Match(line, @"^\d+\s+(?<nodes>\d+)\s+(?<fields>\d+)\s+\d+$");
            if (statistics.Success)
            {
                declaredNodeCount = int.Parse(statistics.Groups["nodes"].Value);
                declaredFieldCount = int.Parse(statistics.Groups["fields"].Value);
                foundStatistics = true;
            }
            continue;
        }

        var terminator = Regex.Match(line, @"^\*+\s*end of schema\s+(?<identity>SCH_[A-Za-z0-9_]+)\s+\*+$", RegexOptions.IgnoreCase);
        if (terminator.Success)
        {
            Flush();
            identity = terminator.Groups["identity"].Value;
            foundTerminator = true;
            continue;
        }

        if (line.Length == 0)
            continue;
        if (foundTerminator)
            throw new FormatException($"Unexpected data after schema terminator in {Path.GetFileName(path)}:{lineNumber}.");

        var nodeMatch = nodeRegex.Match(line);
        if (nodeMatch.Success)
        {
            Flush();
            var typeId = int.Parse(nodeMatch.Groups["id"].Value);
            if (!nodeIds.Add(typeId))
                throw new FormatException($"Duplicate schema node {typeId} in {Path.GetFileName(path)}:{lineNumber}.");
            current = new SchemaNodeBuilder(
                typeId,
                nodeMatch.Groups["name"].Value,
                nodeMatch.Groups["desc"].Value,
                ParseBit(nodeMatch.Groups["transmit"].Value),
                int.Parse(nodeMatch.Groups["fields"].Value),
                ParseBit(nodeMatch.Groups["variable"].Value));
            continue;
        }

        var fieldMatch = fieldRegex.Match(line);
        if (fieldMatch.Success && current is not null)
        {
            current.Fields.Add(new SchemaField(
                fieldMatch.Groups["name"].Value,
                fieldMatch.Groups["type"].Value[0],
                ParseBit(fieldMatch.Groups["transmit"].Value),
                int.Parse(fieldMatch.Groups["class"].Value),
                int.Parse(fieldMatch.Groups["elements"].Value)));
            if (!"bcdfhilnpqtuvw".Contains(current.Fields[^1].Type))
                throw new FormatException($"Unsupported schema field type {current.Fields[^1].Type} in {Path.GetFileName(path)}:{lineNumber}.");
            if (current.Fields[^1].ElementCount < 0)
                throw new FormatException($"Negative element count in {Path.GetFileName(path)}:{lineNumber}.");
            continue;
        }

        throw new FormatException($"Unrecognized schema line in {Path.GetFileName(path)}:{lineNumber}: {line}");
    }

    Flush();
    if (!foundStatistics || !foundTerminator)
        throw new FormatException($"Schema header or terminator is missing in {Path.GetFileName(path)}.");
    var fields = nodes.Sum(static node => node.Fields.Length);
    if (nodes.Count != declaredNodeCount || fields != declaredFieldCount)
        throw new FormatException($"Schema statistics mismatch in {Path.GetFileName(path)}: expected {declaredNodeCount}/{declaredFieldCount}, parsed {nodes.Count}/{fields}.");
    foreach (var node in nodes)
    {
        var hasVariableField = false;
        foreach (var field in node.Fields)
        {
            if (field.Type != 'p' && field.NodeClass != 0)
                throw new FormatException($"Non-pointer field {node.Name}.{field.Name} has pointer class {field.NodeClass} in {Path.GetFileName(path)}.");
            if (field.Type == 'p' && field.NodeClass is > 0 and < 1000 && !nodeIds.Contains(field.NodeClass))
                throw new FormatException($"Pointer field {node.Name}.{field.Name} references unknown concrete class {field.NodeClass} in {Path.GetFileName(path)}.");
            hasVariableField |= field.ElementCount == 1;
        }
        if (node.Variable != hasVariableField)
            throw new FormatException($"Schema node {node.Name} variable flag does not match its field declarations in {Path.GetFileName(path)}.");
    }

    var last = identity.LastIndexOf('_');
    var schemaNumberText = last >= 4 ? identity.AsSpan(last + 1) : identity.AsSpan(4);
    if (!int.TryParse(schemaNumberText, out var schemaNumber))
        throw new FormatException($"Invalid schema identity {identity} in {Path.GetFileName(path)}.");
    if (declaredModelerVersion < 0)
        throw new FormatException($"Invalid modeler version in schema identity {identity}.");

    return new SchemaFile(identity, Path.GetFileName(path), declaredModelerVersion, schemaNumber, nodes.ToArray());

    void Flush()
    {
        if (current is null)
            return;

        if (current.Fields.Count != current.FieldCount)
            throw new FormatException($"Schema node {current.Name} declares {current.FieldCount} fields but parsed {current.Fields.Count}.");

        nodes.Add(new SchemaNode(
            current.TypeId,
            current.Name,
            current.Description,
            current.Transmit,
            current.FieldCount,
            current.Variable,
            current.Fields.ToArray()));
        current = null;
    }
}

static bool ParseBit(string value) => value switch
{
    "0" => false,
    "1" => true,
    _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Expected schema bit 0 or 1."),
};

static string Bool(bool value) => value ? "true" : "false";
static string Escape(string value) => value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);

sealed class SchemaNodeBuilder
{
    public SchemaNodeBuilder(SchemaNodeType typeId, string name, string description, bool transmit, SchemaFieldCount fieldCount, bool variable)
    {
        TypeId = typeId;
        Name = name;
        Description = description;
        Transmit = transmit;
        FieldCount = fieldCount;
        Variable = variable;
    }

    public SchemaNodeType TypeId { get; }
    public string Name { get; }
    public string Description { get; }
    public bool Transmit { get; }
    public SchemaFieldCount FieldCount { get; }
    public bool Variable { get; }
    public List<SchemaField> Fields { get; } = new();
}

readonly record struct SchemaNode(
    SchemaNodeType TypeId,
    string Name,
    string Description,
    bool Transmit,
    SchemaFieldCount FieldCount,
    bool Variable,
    SchemaField[] Fields);

readonly record struct SchemaField(
    string Name,
    char Type,
    bool Transmit,
    SchemaNodeClass NodeClass,
    SchemaElementCount ElementCount);

readonly record struct SchemaFile(
    string Identity,
    string ResourceFileName,
    int ModelerVersion,
    int SchemaNumber,
    SchemaNode[] Nodes);
