#!/usr/bin/env dotnet run
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.RegularExpressions;

static string ScriptPath([CallerFilePath] string path = "") => path;
var root = Path.GetFullPath(Path.Combine(Path.GetDirectoryName(ScriptPath())!, ".."));
var exports = File.ReadAllText(Path.Combine(root, "src/ProjectGmKernel.Native/KernelExports.cs"));
var runtime = string.Join("\n", Directory.GetFiles(Path.Combine(root, "src/ProjectGmKernel.Native/Runtime"), "KernelRuntime*.cs").Select(File.ReadAllText));
var functions = new SortedDictionary<string, string>(StringComparer.Ordinal);
foreach (Match entry in Regex.Matches(exports, "EntryPoint = \"(PK_[^\"]+)\""))
{
    var name = entry.Groups[1].Value;
    var body = Body(exports, name);
    if (!body.Contains("ConcurrencyKind."))
    {
        var call = Regex.Match(body, @"KernelRuntime\.(\w+)\(");
        if (!call.Success) throw new InvalidOperationException("Missing dispatch: " + name);
        body = Body(runtime, call.Groups[1].Value);
    }
    var kinds = Regex.Matches(body, @"ConcurrencyKind\.(\w+)").Select(m => m.Groups[1].Value).Distinct().ToArray();
    var kind = kinds.Length == 1 ? kinds[0] : name == "PK_THREAD_chain_start" ? "Local" : throw new InvalidOperationException("Ambiguous dispatch: " + name);
    if (kind != "Unprotected" && body.Contains("AccessKind.SessionControl")) kind = "Exclusive";
    functions.Add(name, kind);
}
var output = new StringBuilder("// <auto-generated />\n// Run scripts/GenerateFunctionCatalog.cs after changing public dispatch metadata.\nnamespace ProjectGmKernel.Native.Runtime;\n\ninternal static class FunctionCatalog\n{\n");
output.AppendLine($"    internal const int Count = {functions.Count};");
output.AppendLine("    internal static ReadOnlySpan<byte> Name(KernelFunctionId id) => id switch\n    {");
var index = 0;
foreach (var (name, _) in functions) output.AppendLine($"        {++index} => \"{name}\"u8,");
output.AppendLine("        _ => default,\n    };\n");
output.AppendLine("    internal static ConcurrencyKind Concurrency(KernelFunctionId id) => id switch\n    {");
index = 0;
foreach (var (_, kind) in functions) output.AppendLine($"        {++index} => ConcurrencyKind.{kind},");
output.AppendLine("        _ => ConcurrencyKind.Exclusive,\n    };\n}");
var outputPath = Path.Combine(root, "src/ProjectGmKernel.Native/Runtime/FunctionCatalog.generated.cs");
if (args.Contains("--check"))
{
    if (!File.Exists(outputPath) || File.ReadAllText(outputPath) != output.ToString())
        throw new InvalidOperationException("Function catalog is stale; run scripts/GenerateFunctionCatalog.cs.");
    Console.WriteLine($"Function catalog: {functions.Count} implemented dispatch descriptors verified.");
}
else
{
    File.WriteAllText(outputPath, output.ToString());
    Console.WriteLine($"Generated {functions.Count} implemented function descriptors.");
}

static string Body(string source, string name)
{
    var match = Regex.Match(source, @"(?:public|internal|private) static [^\n]+\b" + Regex.Escape(name) + @"\(");
    if (!match.Success) throw new InvalidOperationException("Cannot locate " + name);
    var start = source.IndexOf('\n', match.Index);
    var brace = source.IndexOf('{', start);
    var expression = source.IndexOf("=>", start, StringComparison.Ordinal);
    if (expression >= 0 && expression < brace)
        return source[expression..(source.IndexOf(';', expression) + 1)];
    var depth = 1;
    var end = brace + 1;
    while (depth != 0)
    {
        if (source[end] == '{') depth++;
        else if (source[end] == '}') depth--;
        end++;
    }
    return source[brace..end];
}
